manager_url: "http://localhost:3009"
bootstrap_token: "dev-smtp-org-1-bootstrap-token"
nats_ca_file: "configs/nats/certs/ca.pem"

smtp:
  host: "localhost "
  port: 1025
  from: "noreply@cactus.local"
  auth: "none"
  tls: "none"
