// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewFile = `-- name: CreateNewFile :one
INSERT INTO "file" (message_id, workflow_run_step_id, "name", bucket, object_key, content_type, size_bytes, hash, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, message_id, workflow_run_step_id, name, bucket, object_key, content_type, size_bytes, hash, metadata, created_at, deleted_at
`

type CreateNewFileParams struct {
	MessageID         pgtype.Int4 `json:"message_id"`
	WorkflowRunStepID pgtype.Int4 `json:"workflow_run_step_id"`
	Name              string      `json:"name"`
	Bucket            string      `json:"bucket"`
	ObjectKey         string      `json:"object_key"`
	ContentType       string      `json:"content_type"`
	SizeBytes         int32       `json:"size_bytes"`
	Hash              string      `json:"hash"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateNewFile(ctx context.Context, arg CreateNewFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createNewFile,
		arg.MessageID,
		arg.WorkflowRunStepID,
		arg.Name,
		arg.Bucket,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Hash,
		arg.Metadata,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.WorkflowRunStepID,
		&i.Name,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Hash,
		&i.Metadata,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNewFileByID = `-- name: GetNewFileByID :one
SELECT id, message_id, workflow_run_step_id, name, bucket, object_key, content_type, size_bytes, hash, metadata, created_at, deleted_at FROM "file"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNewFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getNewFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.WorkflowRunStepID,
		&i.Name,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Hash,
		&i.Metadata,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNewFileByObjectKey = `-- name: GetNewFileByObjectKey :one
SELECT id, message_id, workflow_run_step_id, name, bucket, object_key, content_type, size_bytes, hash, metadata, created_at, deleted_at FROM "file"
WHERE object_key = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetNewFileByObjectKey(ctx context.Context, objectKey string) (File, error) {
	row := q.db.QueryRow(ctx, getNewFileByObjectKey, objectKey)
	var i File
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.WorkflowRunStepID,
		&i.Name,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Hash,
		&i.Metadata,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNewFilesByMessageID = `-- name: ListNewFilesByMessageID :many
SELECT id, message_id, workflow_run_step_id, name, bucket, object_key, content_type, size_bytes, hash, metadata, created_at, deleted_at FROM "file"
WHERE message_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListNewFilesByMessageID(ctx context.Context, messageID pgtype.Int4) ([]File, error) {
	rows, err := q.db.Query(ctx, listNewFilesByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.WorkflowRunStepID,
			&i.Name,
			&i.Bucket,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Hash,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewFilesByRunStepID = `-- name: ListNewFilesByRunStepID :many
SELECT id, message_id, workflow_run_step_id, name, bucket, object_key, content_type, size_bytes, hash, metadata, created_at, deleted_at FROM "file"
WHERE workflow_run_step_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListNewFilesByRunStepID(ctx context.Context, workflowRunStepID pgtype.Int4) ([]File, error) {
	rows, err := q.db.Query(ctx, listNewFilesByRunStepID, workflowRunStepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.WorkflowRunStepID,
			&i.Name,
			&i.Bucket,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Hash,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNewFile = `-- name: SoftDeleteNewFile :exec
UPDATE "file"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNewFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteNewFile, id)
	return err
}
