// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewMessage = `-- name: CreateNewMessage :one
INSERT INTO "message" (workflow_id, external_message_id, overridden_priority, value, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at
`

type CreateNewMessageParams struct {
	WorkflowID         int32       `json:"workflow_id"`
	ExternalMessageID  pgtype.Text `json:"external_message_id"`
	OverriddenPriority pgtype.Int4 `json:"overridden_priority"`
	Value              []byte      `json:"value"`
	Status             string      `json:"status"`
}

func (q *Queries) CreateNewMessage(ctx context.Context, arg CreateNewMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createNewMessage,
		arg.WorkflowID,
		arg.ExternalMessageID,
		arg.OverriddenPriority,
		arg.Value,
		arg.Status,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ExternalMessageID,
		&i.OverriddenPriority,
		&i.Value,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageStatusByID = `-- name: GetMessageStatusByID :one
SELECT m.id, m.status AS message_status, m.created_at,
       wr.id AS workflow_run_id, wr.status AS workflow_status,
       wr.started_at AS run_started_at, wr.completed_at AS run_completed_at,
       wr.error_message AS run_error_message
FROM "message" m
LEFT JOIN "workflow_run" wr ON wr.message_id = m.id
WHERE m.id = $1 AND m.deleted_at IS NULL
ORDER BY wr.id DESC
LIMIT 1
`

type GetMessageStatusByIDRow struct {
	ID              int32            `json:"id"`
	MessageStatus   string           `json:"message_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	WorkflowRunID   pgtype.Int4      `json:"workflow_run_id"`
	WorkflowStatus  pgtype.Text      `json:"workflow_status"`
	RunStartedAt    pgtype.Timestamp `json:"run_started_at"`
	RunCompletedAt  pgtype.Timestamp `json:"run_completed_at"`
	RunErrorMessage pgtype.Text      `json:"run_error_message"`
}

// Status API: returns message + latest workflow_run status (per D-20, D-21)
func (q *Queries) GetMessageStatusByID(ctx context.Context, id int32) (GetMessageStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageStatusByID, id)
	var i GetMessageStatusByIDRow
	err := row.Scan(
		&i.ID,
		&i.MessageStatus,
		&i.CreatedAt,
		&i.WorkflowRunID,
		&i.WorkflowStatus,
		&i.RunStartedAt,
		&i.RunCompletedAt,
		&i.RunErrorMessage,
	)
	return i, err
}

const getNewMessageByID = `-- name: GetNewMessageByID :one
SELECT id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at FROM "message"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNewMessageByID(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRow(ctx, getNewMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ExternalMessageID,
		&i.OverriddenPriority,
		&i.Value,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNewMessagesByWorkflowID = `-- name: ListNewMessagesByWorkflowID :many
SELECT id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at FROM "message"
WHERE workflow_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListNewMessagesByWorkflowID(ctx context.Context, workflowID int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, listNewMessagesByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.ExternalMessageID,
			&i.OverriddenPriority,
			&i.Value,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNewMessage = `-- name: SoftDeleteNewMessage :exec
UPDATE "message"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNewMessage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteNewMessage, id)
	return err
}

const updateNewMessageStatus = `-- name: UpdateNewMessageStatus :one
UPDATE "message"
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at
`

type UpdateNewMessageStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNewMessageStatus(ctx context.Context, arg UpdateNewMessageStatusParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateNewMessageStatus, arg.ID, arg.Status)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ExternalMessageID,
		&i.OverriddenPriority,
		&i.Value,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
