// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createNewMessage = `-- name: CreateNewMessage :one
INSERT INTO "message" (workflow_id, external_message_id, overridden_priority, value, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at
`

type CreateNewMessageParams struct {
	WorkflowID         int32           `json:"workflow_id"`
	ExternalMessageID  sql.NullString  `json:"external_message_id"`
	OverriddenPriority sql.NullInt32   `json:"overridden_priority"`
	Value              json.RawMessage `json:"value"`
	Status             string          `json:"status"`
}

func (q *Queries) CreateNewMessage(ctx context.Context, arg CreateNewMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createNewMessage,
		arg.WorkflowID,
		arg.ExternalMessageID,
		arg.OverriddenPriority,
		arg.Value,
		arg.Status,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ExternalMessageID,
		&i.OverriddenPriority,
		&i.Value,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNewMessageByID = `-- name: GetNewMessageByID :one
SELECT id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at FROM "message"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNewMessageByID(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRowContext(ctx, getNewMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ExternalMessageID,
		&i.OverriddenPriority,
		&i.Value,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNewMessagesByWorkflowID = `-- name: ListNewMessagesByWorkflowID :many
SELECT id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at FROM "message"
WHERE workflow_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListNewMessagesByWorkflowID(ctx context.Context, workflowID int32) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listNewMessagesByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.ExternalMessageID,
			&i.OverriddenPriority,
			&i.Value,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNewMessage = `-- name: SoftDeleteNewMessage :exec
UPDATE "message"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNewMessage(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteNewMessage, id)
	return err
}

const updateNewMessageStatus = `-- name: UpdateNewMessageStatus :one
UPDATE "message"
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, external_message_id, overridden_priority, value, status, created_at, updated_at, deleted_at
`

type UpdateNewMessageStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNewMessageStatus(ctx context.Context, arg UpdateNewMessageStatusParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateNewMessageStatus, arg.ID, arg.Status)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ExternalMessageID,
		&i.OverriddenPriority,
		&i.Value,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
