// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permission_role.sql

package db

import (
	"context"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO "permission_role" (permission_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPermissionToRoleParams struct {
	PermissionID int32 `json:"permission_id"`
	RoleID       int32 `json:"role_id"`
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, addPermissionToRole, arg.PermissionID, arg.RoleID)
	return err
}

const listPermissionsByRoleID = `-- name: ListPermissionsByRoleID :many
SELECT p.id, p.slug, p.is_private FROM "permission" p
JOIN "permission_role" pr ON pr.permission_id = p.id
WHERE pr.role_id = $1
ORDER BY p.slug
`

func (q *Queries) ListPermissionsByRoleID(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Slug, &i.IsPrivate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUserID = `-- name: ListPermissionsByUserID :many
SELECT DISTINCT p.id, p.slug, p.is_private FROM "permission" p
JOIN "permission_role" pr ON pr.permission_id = p.id
JOIN "role_user" ru ON ru.role_id = pr.role_id
WHERE ru.user_id = $1
ORDER BY p.slug
`

func (q *Queries) ListPermissionsByUserID(ctx context.Context, userID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Slug, &i.IsPrivate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM "permission_role"
WHERE permission_id = $1 AND role_id = $2
`

type RemovePermissionFromRoleParams struct {
	PermissionID int32 `json:"permission_id"`
	RoleID       int32 `json:"role_id"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.PermissionID, arg.RoleID)
	return err
}
