// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role_user.sql

package db

import (
	"context"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO "role_user" (role_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	RoleID int32 `json:"role_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.RoleID, arg.UserID)
	return err
}

const listRolesByUserID = `-- name: ListRolesByUserID :many
SELECT r.id, r.organization_id, r.name, r.description, r.is_system, r.created_at, r.updated_at FROM "role" r
JOIN "role_user" ru ON ru.role_id = r.id
WHERE ru.user_id = $1
ORDER BY r."name"
`

func (q *Queries) ListRolesByUserID(ctx context.Context, userID int32) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRoleID = `-- name: ListUsersByRoleID :many
SELECT u.id, u.organization_id, u.last_name, u.first_name, u.patronymic, u.email, u.password, u.reset_password_after_login, u.created_at, u.updated_at, u.deleted_at FROM "user" u
JOIN "role_user" ru ON ru.user_id = u.id
WHERE ru.role_id = $1 AND u.deleted_at IS NULL
ORDER BY u.last_name, u.first_name
`

func (q *Queries) ListUsersByRoleID(ctx context.Context, roleID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.LastName,
			&i.FirstName,
			&i.Patronymic,
			&i.Email,
			&i.Password,
			&i.ResetPasswordAfterLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM "role_user"
WHERE role_id = $1 AND user_id = $2
`

type RemoveRoleFromUserParams struct {
	RoleID int32 `json:"role_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.RoleID, arg.UserID)
	return err
}
