// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: system.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSystem = `-- name: CreateSystem :one
INSERT INTO "system" (
    organization_id,
    user_creator_id,
    "name",
    description,
    is_active,
    priority,
    public_token,
    private_token
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, user_creator_id, name, description, is_active, priority, public_token, private_token, created_at, updated_at, deleted_at
`

type CreateSystemParams struct {
	OrganizationID pgtype.Int4 `json:"organization_id"`
	UserCreatorID  pgtype.Int4 `json:"user_creator_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	IsActive       bool        `json:"is_active"`
	Priority       int32       `json:"priority"`
	PublicToken    pgtype.Text `json:"public_token"`
	PrivateToken   pgtype.Text `json:"private_token"`
}

func (q *Queries) CreateSystem(ctx context.Context, arg CreateSystemParams) (System, error) {
	row := q.db.QueryRow(ctx, createSystem,
		arg.OrganizationID,
		arg.UserCreatorID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.Priority,
		arg.PublicToken,
		arg.PrivateToken,
	)
	var i System
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserCreatorID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Priority,
		&i.PublicToken,
		&i.PrivateToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemByID = `-- name: GetSystemByID :one
SELECT id, organization_id, user_creator_id, name, description, is_active, priority, public_token, private_token, created_at, updated_at, deleted_at FROM "system"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSystemByID(ctx context.Context, id int32) (System, error) {
	row := q.db.QueryRow(ctx, getSystemByID, id)
	var i System
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserCreatorID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Priority,
		&i.PublicToken,
		&i.PrivateToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemByPublicToken = `-- name: GetSystemByPublicToken :one
SELECT id, organization_id, user_creator_id, name, description, is_active, priority, public_token, private_token, created_at, updated_at, deleted_at FROM "system"
WHERE public_token = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSystemByPublicToken(ctx context.Context, publicToken pgtype.Text) (System, error) {
	row := q.db.QueryRow(ctx, getSystemByPublicToken, publicToken)
	var i System
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserCreatorID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Priority,
		&i.PublicToken,
		&i.PrivateToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSystemsByOrganizationID = `-- name: ListSystemsByOrganizationID :many
SELECT id, organization_id, user_creator_id, name, description, is_active, priority, public_token, private_token, created_at, updated_at, deleted_at FROM "system"
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListSystemsByOrganizationID(ctx context.Context, organizationID pgtype.Int4) ([]System, error) {
	rows, err := q.db.Query(ctx, listSystemsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserCreatorID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.Priority,
			&i.PublicToken,
			&i.PrivateToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSystem = `-- name: SoftDeleteSystem :exec
UPDATE "system"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSystem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteSystem, id)
	return err
}

const updateSystem = `-- name: UpdateSystem :one
UPDATE "system"
SET "name" = $2, description = $3, is_active = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, user_creator_id, name, description, is_active, priority, public_token, private_token, created_at, updated_at, deleted_at
`

type UpdateSystemParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateSystem(ctx context.Context, arg UpdateSystemParams) (System, error) {
	row := q.db.QueryRow(ctx, updateSystem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i System
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserCreatorID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Priority,
		&i.PublicToken,
		&i.PrivateToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
