// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: system_token.sql

package db

import (
	"context"
)

const activateSystemToken = `-- name: ActivateSystemToken :exec
UPDATE "system_token"
SET is_active = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ActivateSystemToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, activateSystemToken, id)
	return err
}

const createSystemToken = `-- name: CreateSystemToken :one
INSERT INTO "system_token" (system_id, name, public_token, private_token, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, system_id, name, public_token, private_token, is_active, created_at, updated_at, deleted_at
`

type CreateSystemTokenParams struct {
	SystemID     int32  `json:"system_id"`
	Name         string `json:"name"`
	PublicToken  string `json:"public_token"`
	PrivateToken string `json:"private_token"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateSystemToken(ctx context.Context, arg CreateSystemTokenParams) (SystemToken, error) {
	row := q.db.QueryRow(ctx, createSystemToken,
		arg.SystemID,
		arg.Name,
		arg.PublicToken,
		arg.PrivateToken,
		arg.IsActive,
	)
	var i SystemToken
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.PublicToken,
		&i.PrivateToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateSystemToken = `-- name: DeactivateSystemToken :exec
UPDATE "system_token"
SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateSystemToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateSystemToken, id)
	return err
}

const getSystemTokenByID = `-- name: GetSystemTokenByID :one
SELECT id, system_id, name, public_token, private_token, is_active, created_at, updated_at, deleted_at FROM "system_token"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSystemTokenByID(ctx context.Context, id int32) (SystemToken, error) {
	row := q.db.QueryRow(ctx, getSystemTokenByID, id)
	var i SystemToken
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.PublicToken,
		&i.PrivateToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemTokenByPublicToken = `-- name: GetSystemTokenByPublicToken :one
SELECT id, system_id, name, public_token, private_token, is_active, created_at, updated_at, deleted_at FROM "system_token"
WHERE public_token = $1 AND is_active = TRUE AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSystemTokenByPublicToken(ctx context.Context, publicToken string) (SystemToken, error) {
	row := q.db.QueryRow(ctx, getSystemTokenByPublicToken, publicToken)
	var i SystemToken
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.PublicToken,
		&i.PrivateToken,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSystemTokensBySystemID = `-- name: ListSystemTokensBySystemID :many
SELECT id, system_id, name, public_token, private_token, is_active, created_at, updated_at, deleted_at FROM "system_token"
WHERE system_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListSystemTokensBySystemID(ctx context.Context, systemID int32) ([]SystemToken, error) {
	rows, err := q.db.Query(ctx, listSystemTokensBySystemID, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemToken
	for rows.Next() {
		var i SystemToken
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Name,
			&i.PublicToken,
			&i.PrivateToken,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSystemToken = `-- name: SoftDeleteSystemToken :exec
UPDATE "system_token"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSystemToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteSystemToken, id)
	return err
}
