// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_version_input.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowVersionInput = `-- name: CreateWorkflowVersionInput :one
INSERT INTO "workflow_version_input" (workflow_version_id, name, type, required, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_version_id, name, type, required, description, created_at, updated_at, deleted_at
`

type CreateWorkflowVersionInputParams struct {
	WorkflowVersionID int32       `json:"workflow_version_id"`
	Name              string      `json:"name"`
	Type              string      `json:"type"`
	Required          bool        `json:"required"`
	Description       pgtype.Text `json:"description"`
}

func (q *Queries) CreateWorkflowVersionInput(ctx context.Context, arg CreateWorkflowVersionInputParams) (WorkflowVersionInput, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersionInput,
		arg.WorkflowVersionID,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.Description,
	)
	var i WorkflowVersionInput
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowVersionInputByID = `-- name: GetWorkflowVersionInputByID :one
SELECT id, workflow_version_id, name, type, required, description, created_at, updated_at, deleted_at FROM "workflow_version_input"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowVersionInputByID(ctx context.Context, id int32) (WorkflowVersionInput, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionInputByID, id)
	var i WorkflowVersionInput
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkflowVersionInputs = `-- name: ListWorkflowVersionInputs :many
SELECT id, workflow_version_id, name, type, required, description, created_at, updated_at, deleted_at FROM "workflow_version_input"
WHERE workflow_version_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListWorkflowVersionInputs(ctx context.Context, workflowVersionID int32) ([]WorkflowVersionInput, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersionInputs, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersionInput
	for rows.Next() {
		var i WorkflowVersionInput
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.Name,
			&i.Type,
			&i.Required,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowVersionInput = `-- name: SoftDeleteWorkflowVersionInput :exec
UPDATE "workflow_version_input"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowVersionInput(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowVersionInput, id)
	return err
}

const updateWorkflowVersionInput = `-- name: UpdateWorkflowVersionInput :one
UPDATE "workflow_version_input"
SET name = $2, type = $3, required = $4, description = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_version_id, name, type, required, description, created_at, updated_at, deleted_at
`

type UpdateWorkflowVersionInputParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Required    bool        `json:"required"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateWorkflowVersionInput(ctx context.Context, arg UpdateWorkflowVersionInputParams) (WorkflowVersionInput, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionInput,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.Description,
	)
	var i WorkflowVersionInput
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
