// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_version.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO "workflow_version" (workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at
`

type CreateWorkflowVersionParams struct {
	WorkflowID      int32       `json:"workflow_id"`
	CreatedByUserID pgtype.Int4 `json:"created_by_user_id"`
	VersionNumber   int32       `json:"version_number"`
	IsValid         bool        `json:"is_valid"`
	IsActive        bool        `json:"is_active"`
	TrafficWeight   int32       `json:"traffic_weight"`
	IsControlGroup  bool        `json:"is_control_group"`
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion,
		arg.WorkflowID,
		arg.CreatedByUserID,
		arg.VersionNumber,
		arg.IsValid,
		arg.IsActive,
		arg.TrafficWeight,
		arg.IsControlGroup,
	)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaxVersionNumberByWorkflowID = `-- name: GetMaxVersionNumberByWorkflowID :one
SELECT COALESCE(MAX(version_number), 0)::int FROM "workflow_version"
WHERE workflow_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMaxVersionNumberByWorkflowID(ctx context.Context, workflowID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxVersionNumberByWorkflowID, workflowID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getWorkflowVersionByID = `-- name: GetWorkflowVersionByID :one
SELECT id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at FROM "workflow_version"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowVersionByID(ctx context.Context, id int32) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByID, id)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveWorkflowVersions = `-- name: ListActiveWorkflowVersions :many
SELECT id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at FROM "workflow_version"
WHERE workflow_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY version_number
`

func (q *Queries) ListActiveWorkflowVersions(ctx context.Context, workflowID int32) ([]WorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowVersions, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersion
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.CreatedByUserID,
			&i.VersionNumber,
			&i.IsValid,
			&i.IsActive,
			&i.TrafficWeight,
			&i.IsControlGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersionsByWorkflowID = `-- name: ListWorkflowVersionsByWorkflowID :many
SELECT id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at FROM "workflow_version"
WHERE workflow_id = $1 AND deleted_at IS NULL
ORDER BY version_number
`

func (q *Queries) ListWorkflowVersionsByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersionsByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersion
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.CreatedByUserID,
			&i.VersionNumber,
			&i.IsValid,
			&i.IsActive,
			&i.TrafficWeight,
			&i.IsControlGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowVersion = `-- name: SoftDeleteWorkflowVersion :exec
UPDATE "workflow_version"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowVersion(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowVersion, id)
	return err
}

const updateWorkflowVersionActive = `-- name: UpdateWorkflowVersionActive :one
UPDATE "workflow_version"
SET is_active = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at
`

type UpdateWorkflowVersionActiveParams struct {
	ID       int32 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateWorkflowVersionActive(ctx context.Context, arg UpdateWorkflowVersionActiveParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionActive, arg.ID, arg.IsActive)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowVersionTrafficWeight = `-- name: UpdateWorkflowVersionTrafficWeight :one
UPDATE "workflow_version"
SET traffic_weight = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at
`

type UpdateWorkflowVersionTrafficWeightParams struct {
	ID            int32 `json:"id"`
	TrafficWeight int32 `json:"traffic_weight"`
}

func (q *Queries) UpdateWorkflowVersionTrafficWeight(ctx context.Context, arg UpdateWorkflowVersionTrafficWeightParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionTrafficWeight, arg.ID, arg.TrafficWeight)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowVersionValid = `-- name: UpdateWorkflowVersionValid :one
UPDATE "workflow_version"
SET is_valid = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, is_valid, is_active, traffic_weight, is_control_group, created_at, updated_at, deleted_at
`

type UpdateWorkflowVersionValidParams struct {
	ID      int32 `json:"id"`
	IsValid bool  `json:"is_valid"`
}

func (q *Queries) UpdateWorkflowVersionValid(ctx context.Context, arg UpdateWorkflowVersionValidParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionValid, arg.ID, arg.IsValid)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
