// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_run_step.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningStepsByRevisionInWindow = `-- name: CountRunningStepsByRevisionInWindow :one
SELECT COUNT(*) AS cnt
FROM "workflow_run_step" wrs
JOIN "workflow_step" ws ON ws.id = wrs.workflow_step_id
WHERE ws.worker_settings_revision_id = $1
  AND wrs.started_at >= $2
  AND wrs.status IN ('running', 'completed')
`

type CountRunningStepsByRevisionInWindowParams struct {
	WorkerSettingsRevisionID pgtype.Int4      `json:"worker_settings_revision_id"`
	StartedAt                pgtype.Timestamp `json:"started_at"`
}

func (q *Queries) CountRunningStepsByRevisionInWindow(ctx context.Context, arg CountRunningStepsByRevisionInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningStepsByRevisionInWindow, arg.WorkerSettingsRevisionID, arg.StartedAt)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createWorkflowRunStep = `-- name: CreateWorkflowRunStep :one
INSERT INTO "workflow_run_step" (workflow_run_id, workflow_step_id, worker_id, temporal_step_id, status, input_data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workflow_run_id, workflow_step_id, worker_id, temporal_step_id, status, outcome, input_data, output_data, started_at, completed_at, error_message
`

type CreateWorkflowRunStepParams struct {
	WorkflowRunID  int32       `json:"workflow_run_id"`
	WorkflowStepID int32       `json:"workflow_step_id"`
	WorkerID       pgtype.Int4 `json:"worker_id"`
	TemporalStepID pgtype.Text `json:"temporal_step_id"`
	Status         string      `json:"status"`
	InputData      []byte      `json:"input_data"`
}

func (q *Queries) CreateWorkflowRunStep(ctx context.Context, arg CreateWorkflowRunStepParams) (WorkflowRunStep, error) {
	row := q.db.QueryRow(ctx, createWorkflowRunStep,
		arg.WorkflowRunID,
		arg.WorkflowStepID,
		arg.WorkerID,
		arg.TemporalStepID,
		arg.Status,
		arg.InputData,
	)
	var i WorkflowRunStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.WorkflowStepID,
		&i.WorkerID,
		&i.TemporalStepID,
		&i.Status,
		&i.Outcome,
		&i.InputData,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getWorkflowRunStepByID = `-- name: GetWorkflowRunStepByID :one
SELECT id, workflow_run_id, workflow_step_id, worker_id, temporal_step_id, status, outcome, input_data, output_data, started_at, completed_at, error_message FROM "workflow_run_step"
WHERE id = $1
`

func (q *Queries) GetWorkflowRunStepByID(ctx context.Context, id int32) (WorkflowRunStep, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunStepByID, id)
	var i WorkflowRunStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.WorkflowStepID,
		&i.WorkerID,
		&i.TemporalStepID,
		&i.Status,
		&i.Outcome,
		&i.InputData,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const listWorkflowRunStepsByRunID = `-- name: ListWorkflowRunStepsByRunID :many
SELECT id, workflow_run_id, workflow_step_id, worker_id, temporal_step_id, status, outcome, input_data, output_data, started_at, completed_at, error_message FROM "workflow_run_step"
WHERE workflow_run_id = $1
ORDER BY id
`

func (q *Queries) ListWorkflowRunStepsByRunID(ctx context.Context, workflowRunID int32) ([]WorkflowRunStep, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunStepsByRunID, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRunStep
	for rows.Next() {
		var i WorkflowRunStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.WorkflowStepID,
			&i.WorkerID,
			&i.TemporalStepID,
			&i.Status,
			&i.Outcome,
			&i.InputData,
			&i.OutputData,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStepStarted = `-- name: UpdateWorkflowRunStepStarted :one
UPDATE "workflow_run_step"
SET status = 'running', worker_id = $2, started_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, workflow_run_id, workflow_step_id, worker_id, temporal_step_id, status, outcome, input_data, output_data, started_at, completed_at, error_message
`

type UpdateWorkflowRunStepStartedParams struct {
	ID       int32       `json:"id"`
	WorkerID pgtype.Int4 `json:"worker_id"`
}

func (q *Queries) UpdateWorkflowRunStepStarted(ctx context.Context, arg UpdateWorkflowRunStepStartedParams) (WorkflowRunStep, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunStepStarted, arg.ID, arg.WorkerID)
	var i WorkflowRunStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.WorkflowStepID,
		&i.WorkerID,
		&i.TemporalStepID,
		&i.Status,
		&i.Outcome,
		&i.InputData,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const updateWorkflowRunStepStatus = `-- name: UpdateWorkflowRunStepStatus :one
UPDATE "workflow_run_step"
SET status = $2, outcome = $3, output_data = $4, completed_at = $5, error_message = $6
WHERE id = $1
RETURNING id, workflow_run_id, workflow_step_id, worker_id, temporal_step_id, status, outcome, input_data, output_data, started_at, completed_at, error_message
`

type UpdateWorkflowRunStepStatusParams struct {
	ID           int32            `json:"id"`
	Status       string           `json:"status"`
	Outcome      pgtype.Text      `json:"outcome"`
	OutputData   []byte           `json:"output_data"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
	ErrorMessage pgtype.Text      `json:"error_message"`
}

func (q *Queries) UpdateWorkflowRunStepStatus(ctx context.Context, arg UpdateWorkflowRunStepStatusParams) (WorkflowRunStep, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunStepStatus,
		arg.ID,
		arg.Status,
		arg.Outcome,
		arg.OutputData,
		arg.CompletedAt,
		arg.ErrorMessage,
	)
	var i WorkflowRunStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.WorkflowStepID,
		&i.WorkerID,
		&i.TemporalStepID,
		&i.Status,
		&i.Outcome,
		&i.InputData,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}
