// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker_nats_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkerNATSSession = `-- name: CreateWorkerNATSSession :one
INSERT INTO "worker_nats_session" (
    worker_id, bootstrap_token_id, nats_account_public_key,
    nats_user_public_key, nats_user_jwt, permissions
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, worker_id, bootstrap_token_id, nats_account_public_key, nats_user_public_key, nats_user_jwt, permissions, revoked_at, revoked_by_user_id, created_at
`

type CreateWorkerNATSSessionParams struct {
	WorkerID             int32  `json:"worker_id"`
	BootstrapTokenID     int32  `json:"bootstrap_token_id"`
	NatsAccountPublicKey string `json:"nats_account_public_key"`
	NatsUserPublicKey    string `json:"nats_user_public_key"`
	NatsUserJwt          string `json:"nats_user_jwt"`
	Permissions          []byte `json:"permissions"`
}

func (q *Queries) CreateWorkerNATSSession(ctx context.Context, arg CreateWorkerNATSSessionParams) (WorkerNatsSession, error) {
	row := q.db.QueryRow(ctx, createWorkerNATSSession,
		arg.WorkerID,
		arg.BootstrapTokenID,
		arg.NatsAccountPublicKey,
		arg.NatsUserPublicKey,
		arg.NatsUserJwt,
		arg.Permissions,
	)
	var i WorkerNatsSession
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.BootstrapTokenID,
		&i.NatsAccountPublicKey,
		&i.NatsUserPublicKey,
		&i.NatsUserJwt,
		&i.Permissions,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWorkerNATSSessionsByBootstrapToken = `-- name: ListActiveWorkerNATSSessionsByBootstrapToken :many
SELECT id, worker_id, bootstrap_token_id, nats_account_public_key, nats_user_public_key, nats_user_jwt, permissions, revoked_at, revoked_by_user_id, created_at
FROM "worker_nats_session"
WHERE bootstrap_token_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListActiveWorkerNATSSessionsByBootstrapToken(ctx context.Context, bootstrapTokenID int32) ([]WorkerNatsSession, error) {
	rows, err := q.db.Query(ctx, listActiveWorkerNATSSessionsByBootstrapToken, bootstrapTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerNatsSession
	for rows.Next() {
		var i WorkerNatsSession
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.BootstrapTokenID,
			&i.NatsAccountPublicKey,
			&i.NatsUserPublicKey,
			&i.NatsUserJwt,
			&i.Permissions,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkerNATSSession = `-- name: RevokeWorkerNATSSession :one
UPDATE "worker_nats_session"
SET revoked_at = CURRENT_TIMESTAMP,
    revoked_by_user_id = $2
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, worker_id, bootstrap_token_id, nats_account_public_key, nats_user_public_key, nats_user_jwt, permissions, revoked_at, revoked_by_user_id, created_at
`

type RevokeWorkerNATSSessionParams struct {
	ID              int32       `json:"id"`
	RevokedByUserID pgtype.Int4 `json:"revoked_by_user_id"`
}

func (q *Queries) RevokeWorkerNATSSession(ctx context.Context, arg RevokeWorkerNATSSessionParams) (WorkerNatsSession, error) {
	row := q.db.QueryRow(ctx, revokeWorkerNATSSession, arg.ID, arg.RevokedByUserID)
	var i WorkerNatsSession
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.BootstrapTokenID,
		&i.NatsAccountPublicKey,
		&i.NatsUserPublicKey,
		&i.NatsUserJwt,
		&i.Permissions,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const revokeWorkerNATSSessionsByBootstrapToken = `-- name: RevokeWorkerNATSSessionsByBootstrapToken :many
UPDATE "worker_nats_session"
SET revoked_at = CURRENT_TIMESTAMP,
    revoked_by_user_id = $2
WHERE bootstrap_token_id = $1
  AND revoked_at IS NULL
RETURNING id, worker_id, bootstrap_token_id, nats_account_public_key, nats_user_public_key, nats_user_jwt, permissions, revoked_at, revoked_by_user_id, created_at
`

type RevokeWorkerNATSSessionsByBootstrapTokenParams struct {
	BootstrapTokenID int32       `json:"bootstrap_token_id"`
	RevokedByUserID  pgtype.Int4 `json:"revoked_by_user_id"`
}

func (q *Queries) RevokeWorkerNATSSessionsByBootstrapToken(ctx context.Context, arg RevokeWorkerNATSSessionsByBootstrapTokenParams) ([]WorkerNatsSession, error) {
	rows, err := q.db.Query(ctx, revokeWorkerNATSSessionsByBootstrapToken, arg.BootstrapTokenID, arg.RevokedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerNatsSession
	for rows.Next() {
		var i WorkerNatsSession
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.BootstrapTokenID,
			&i.NatsAccountPublicKey,
			&i.NatsUserPublicKey,
			&i.NatsUserJwt,
			&i.Permissions,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
