// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_step_dependency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowStepDependency = `-- name: CreateWorkflowStepDependency :exec
INSERT INTO "workflow_step_dependency" (step_id, depends_on_step_id, outcome)
VALUES ($1, $2, $3)
`

type CreateWorkflowStepDependencyParams struct {
	StepID          int32       `json:"step_id"`
	DependsOnStepID int32       `json:"depends_on_step_id"`
	Outcome         pgtype.Text `json:"outcome"`
}

func (q *Queries) CreateWorkflowStepDependency(ctx context.Context, arg CreateWorkflowStepDependencyParams) error {
	_, err := q.db.Exec(ctx, createWorkflowStepDependency, arg.StepID, arg.DependsOnStepID, arg.Outcome)
	return err
}

const deleteDependenciesByStepID = `-- name: DeleteDependenciesByStepID :exec
DELETE FROM "workflow_step_dependency"
WHERE step_id = $1
`

func (q *Queries) DeleteDependenciesByStepID(ctx context.Context, stepID int32) error {
	_, err := q.db.Exec(ctx, deleteDependenciesByStepID, stepID)
	return err
}

const deleteWorkflowStepDependency = `-- name: DeleteWorkflowStepDependency :exec
DELETE FROM "workflow_step_dependency"
WHERE step_id = $1 AND depends_on_step_id = $2
`

type DeleteWorkflowStepDependencyParams struct {
	StepID          int32 `json:"step_id"`
	DependsOnStepID int32 `json:"depends_on_step_id"`
}

func (q *Queries) DeleteWorkflowStepDependency(ctx context.Context, arg DeleteWorkflowStepDependencyParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflowStepDependency, arg.StepID, arg.DependsOnStepID)
	return err
}

const listDependenciesByVersionID = `-- name: ListDependenciesByVersionID :many
SELECT wsd.step_id, wsd.depends_on_step_id, wsd.outcome
FROM "workflow_step_dependency" wsd
JOIN "workflow_step" ws ON ws.id = wsd.step_id
WHERE ws.workflow_version_id = $1 AND ws.deleted_at IS NULL
ORDER BY wsd.step_id, wsd.depends_on_step_id
`

func (q *Queries) ListDependenciesByVersionID(ctx context.Context, workflowVersionID int32) ([]WorkflowStepDependency, error) {
	rows, err := q.db.Query(ctx, listDependenciesByVersionID, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepDependency
	for rows.Next() {
		var i WorkflowStepDependency
		if err := rows.Scan(&i.StepID, &i.DependsOnStepID, &i.Outcome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepDependencies = `-- name: ListWorkflowStepDependencies :many
SELECT step_id, depends_on_step_id, outcome FROM "workflow_step_dependency"
WHERE step_id = $1
ORDER BY depends_on_step_id
`

func (q *Queries) ListWorkflowStepDependencies(ctx context.Context, stepID int32) ([]WorkflowStepDependency, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepDependencies, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepDependency
	for rows.Next() {
		var i WorkflowStepDependency
		if err := rows.Scan(&i.StepID, &i.DependsOnStepID, &i.Outcome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
