// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker_bootstrap_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWorkersByBootstrapTokenExcludingWorker = `-- name: CountActiveWorkersByBootstrapTokenExcludingWorker :one
SELECT COUNT(DISTINCT s.worker_id)::int
FROM "worker_nats_session" s
JOIN "worker" w ON w.id = s.worker_id
WHERE s.bootstrap_token_id = $1
  AND s.revoked_at IS NULL
  AND w.last_heartbeat_at > CURRENT_TIMESTAMP - ($2::int * INTERVAL '1 second')
  AND ($3::int = 0 OR s.worker_id <> $3::int)
`

type CountActiveWorkersByBootstrapTokenExcludingWorkerParams struct {
	BootstrapTokenID        int32 `json:"bootstrap_token_id"`
	HeartbeatTimeoutSeconds int32 `json:"heartbeat_timeout_seconds"`
	ExcludeWorkerID         int32 `json:"exclude_worker_id"`
}

func (q *Queries) CountActiveWorkersByBootstrapTokenExcludingWorker(ctx context.Context, arg CountActiveWorkersByBootstrapTokenExcludingWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveWorkersByBootstrapTokenExcludingWorker, arg.BootstrapTokenID, arg.HeartbeatTimeoutSeconds, arg.ExcludeWorkerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createWorkerBootstrapToken = `-- name: CreateWorkerBootstrapToken :one
INSERT INTO "worker_bootstrap_token" (
    organization_id, work_type_id, name, description, token_hash,
    max_active_workers, expires_at, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, work_type_id, name, description, token_hash, status, max_active_workers, total_registration_count, expires_at, last_used_at, created_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at, deleted_at
`

type CreateWorkerBootstrapTokenParams struct {
	OrganizationID   int32            `json:"organization_id"`
	WorkTypeID       int32            `json:"work_type_id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	TokenHash        string           `json:"token_hash"`
	MaxActiveWorkers int32            `json:"max_active_workers"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	CreatedByUserID  pgtype.Int4      `json:"created_by_user_id"`
}

func (q *Queries) CreateWorkerBootstrapToken(ctx context.Context, arg CreateWorkerBootstrapTokenParams) (WorkerBootstrapToken, error) {
	row := q.db.QueryRow(ctx, createWorkerBootstrapToken,
		arg.OrganizationID,
		arg.WorkTypeID,
		arg.Name,
		arg.Description,
		arg.TokenHash,
		arg.MaxActiveWorkers,
		arg.ExpiresAt,
		arg.CreatedByUserID,
	)
	var i WorkerBootstrapToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkTypeID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.Status,
		&i.MaxActiveWorkers,
		&i.TotalRegistrationCount,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveWorkerBootstrapTokenByHash = `-- name: GetActiveWorkerBootstrapTokenByHash :one
SELECT id, organization_id, work_type_id, name, description, token_hash, status, max_active_workers, total_registration_count, expires_at, last_used_at, created_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at, deleted_at
FROM "worker_bootstrap_token"
WHERE token_hash = $1
  AND status = 'active'
  AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
LIMIT 1
`

func (q *Queries) GetActiveWorkerBootstrapTokenByHash(ctx context.Context, tokenHash string) (WorkerBootstrapToken, error) {
	row := q.db.QueryRow(ctx, getActiveWorkerBootstrapTokenByHash, tokenHash)
	var i WorkerBootstrapToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkTypeID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.Status,
		&i.MaxActiveWorkers,
		&i.TotalRegistrationCount,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveWorkerBootstrapTokenByHashForUpdate = `-- name: GetActiveWorkerBootstrapTokenByHashForUpdate :one
SELECT id, organization_id, work_type_id, name, description, token_hash, status, max_active_workers, total_registration_count, expires_at, last_used_at, created_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at, deleted_at
FROM "worker_bootstrap_token"
WHERE token_hash = $1
  AND status = 'active'
  AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
FOR UPDATE
`

func (q *Queries) GetActiveWorkerBootstrapTokenByHashForUpdate(ctx context.Context, tokenHash string) (WorkerBootstrapToken, error) {
	row := q.db.QueryRow(ctx, getActiveWorkerBootstrapTokenByHashForUpdate, tokenHash)
	var i WorkerBootstrapToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkTypeID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.Status,
		&i.MaxActiveWorkers,
		&i.TotalRegistrationCount,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkerBootstrapTokensByOrganization = `-- name: ListWorkerBootstrapTokensByOrganization :many
SELECT
    t.id, t.organization_id, t.work_type_id, t.name, t.description, t.token_hash, t.status, t.max_active_workers, t.total_registration_count, t.expires_at, t.last_used_at, t.created_by_user_id, t.revoked_at, t.revoked_by_user_id, t.created_at, t.updated_at, t.deleted_at,
    COALESCE(active_workers.active_worker_count, 0)::int AS active_worker_count
FROM "worker_bootstrap_token" t
LEFT JOIN LATERAL (
    SELECT COUNT(DISTINCT s.worker_id) AS active_worker_count
    FROM "worker_nats_session" s
    JOIN "worker" w ON w.id = s.worker_id
    WHERE s.bootstrap_token_id = t.id
      AND s.revoked_at IS NULL
      AND w.last_heartbeat_at > CURRENT_TIMESTAMP - INTERVAL '90 seconds'
) active_workers ON TRUE
WHERE t.organization_id = $1
  AND t.deleted_at IS NULL
ORDER BY t.created_at DESC, t.id DESC
`

type ListWorkerBootstrapTokensByOrganizationRow struct {
	ID                     int32            `json:"id"`
	OrganizationID         int32            `json:"organization_id"`
	WorkTypeID             int32            `json:"work_type_id"`
	Name                   string           `json:"name"`
	Description            pgtype.Text      `json:"description"`
	TokenHash              string           `json:"token_hash"`
	Status                 string           `json:"status"`
	MaxActiveWorkers       int32            `json:"max_active_workers"`
	TotalRegistrationCount int32            `json:"total_registration_count"`
	ExpiresAt              pgtype.Timestamp `json:"expires_at"`
	LastUsedAt             pgtype.Timestamp `json:"last_used_at"`
	CreatedByUserID        pgtype.Int4      `json:"created_by_user_id"`
	RevokedAt              pgtype.Timestamp `json:"revoked_at"`
	RevokedByUserID        pgtype.Int4      `json:"revoked_by_user_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
	ActiveWorkerCount      int32            `json:"active_worker_count"`
}

func (q *Queries) ListWorkerBootstrapTokensByOrganization(ctx context.Context, organizationID int32) ([]ListWorkerBootstrapTokensByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listWorkerBootstrapTokensByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerBootstrapTokensByOrganizationRow
	for rows.Next() {
		var i ListWorkerBootstrapTokensByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkTypeID,
			&i.Name,
			&i.Description,
			&i.TokenHash,
			&i.Status,
			&i.MaxActiveWorkers,
			&i.TotalRegistrationCount,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedByUserID,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ActiveWorkerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkerBootstrapToken = `-- name: RevokeWorkerBootstrapToken :one
UPDATE "worker_bootstrap_token"
SET status = 'revoked',
    revoked_at = CURRENT_TIMESTAMP,
    revoked_by_user_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, organization_id, work_type_id, name, description, token_hash, status, max_active_workers, total_registration_count, expires_at, last_used_at, created_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at, deleted_at
`

type RevokeWorkerBootstrapTokenParams struct {
	ID              int32       `json:"id"`
	RevokedByUserID pgtype.Int4 `json:"revoked_by_user_id"`
}

func (q *Queries) RevokeWorkerBootstrapToken(ctx context.Context, arg RevokeWorkerBootstrapTokenParams) (WorkerBootstrapToken, error) {
	row := q.db.QueryRow(ctx, revokeWorkerBootstrapToken, arg.ID, arg.RevokedByUserID)
	var i WorkerBootstrapToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkTypeID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.Status,
		&i.MaxActiveWorkers,
		&i.TotalRegistrationCount,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const touchWorkerBootstrapTokenUse = `-- name: TouchWorkerBootstrapTokenUse :one
UPDATE "worker_bootstrap_token"
SET total_registration_count = total_registration_count + 1,
    last_used_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND status = 'active'
  AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
RETURNING id, organization_id, work_type_id, name, description, token_hash, status, max_active_workers, total_registration_count, expires_at, last_used_at, created_by_user_id, revoked_at, revoked_by_user_id, created_at, updated_at, deleted_at
`

func (q *Queries) TouchWorkerBootstrapTokenUse(ctx context.Context, id int32) (WorkerBootstrapToken, error) {
	row := q.db.QueryRow(ctx, touchWorkerBootstrapTokenUse, id)
	var i WorkerBootstrapToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkTypeID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.Status,
		&i.MaxActiveWorkers,
		&i.TotalRegistrationCount,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
