// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_version_input_schema_compatibility.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowVersionInputSchemaCompatibility = `-- name: CreateWorkflowVersionInputSchemaCompatibility :one
INSERT INTO "workflow_version_input_schema_compatibility" (
    workflow_version_id,
    workflow_input_schema_id,
    compatibility_type,
    workflow_input_mapper_id,
    default_values,
    is_active,
    is_default_route,
    created_by_user_id,
    updated_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type CreateWorkflowVersionInputSchemaCompatibilityParams struct {
	WorkflowVersionID     int32       `json:"workflow_version_id"`
	WorkflowInputSchemaID int32       `json:"workflow_input_schema_id"`
	CompatibilityType     string      `json:"compatibility_type"`
	WorkflowInputMapperID pgtype.Int4 `json:"workflow_input_mapper_id"`
	DefaultValues         []byte      `json:"default_values"`
	IsActive              bool        `json:"is_active"`
	IsDefaultRoute        bool        `json:"is_default_route"`
	CreatedByUserID       pgtype.Int4 `json:"created_by_user_id"`
	UpdatedByUserID       pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) CreateWorkflowVersionInputSchemaCompatibility(ctx context.Context, arg CreateWorkflowVersionInputSchemaCompatibilityParams) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersionInputSchemaCompatibility,
		arg.WorkflowVersionID,
		arg.WorkflowInputSchemaID,
		arg.CompatibilityType,
		arg.WorkflowInputMapperID,
		arg.DefaultValues,
		arg.IsActive,
		arg.IsDefaultRoute,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateWorkflowVersionInputSchemaCompatibility = `-- name: DeactivateWorkflowVersionInputSchemaCompatibility :one
UPDATE "workflow_version_input_schema_compatibility"
SET is_active = FALSE,
    is_default_route = FALSE,
    updated_by_user_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type DeactivateWorkflowVersionInputSchemaCompatibilityParams struct {
	ID              int32       `json:"id"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) DeactivateWorkflowVersionInputSchemaCompatibility(ctx context.Context, arg DeactivateWorkflowVersionInputSchemaCompatibilityParams) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, deactivateWorkflowVersionInputSchemaCompatibility, arg.ID, arg.UpdatedByUserID)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveWorkflowVersionInputSchemaCompatibilityByPair = `-- name: GetActiveWorkflowVersionInputSchemaCompatibilityByPair :one
SELECT id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_version_input_schema_compatibility"
WHERE workflow_version_id = $1
  AND workflow_input_schema_id = $2
  AND is_active = TRUE
  AND deleted_at IS NULL
`

type GetActiveWorkflowVersionInputSchemaCompatibilityByPairParams struct {
	WorkflowVersionID     int32 `json:"workflow_version_id"`
	WorkflowInputSchemaID int32 `json:"workflow_input_schema_id"`
}

func (q *Queries) GetActiveWorkflowVersionInputSchemaCompatibilityByPair(ctx context.Context, arg GetActiveWorkflowVersionInputSchemaCompatibilityByPairParams) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, getActiveWorkflowVersionInputSchemaCompatibilityByPair, arg.WorkflowVersionID, arg.WorkflowInputSchemaID)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDefaultRouteForInputSchema = `-- name: GetDefaultRouteForInputSchema :one
SELECT c.id, c.workflow_version_id, c.workflow_input_schema_id, c.compatibility_type, c.workflow_input_mapper_id, c.default_values, c.is_active, c.is_default_route, c.created_by_user_id, c.updated_by_user_id, c.created_at, c.updated_at, c.deleted_at
FROM "workflow_version_input_schema_compatibility" c
JOIN "workflow_version" v ON v.id = c.workflow_version_id
WHERE c.workflow_input_schema_id = $1
  AND c.is_default_route = TRUE
  AND c.is_active = TRUE
  AND c.deleted_at IS NULL
  AND v.deleted_at IS NULL
  AND v.archived_at IS NULL
  AND v.is_active = TRUE
  AND v.is_valid = TRUE
`

func (q *Queries) GetDefaultRouteForInputSchema(ctx context.Context, workflowInputSchemaID int32) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, getDefaultRouteForInputSchema, workflowInputSchemaID)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowVersionInputSchemaCompatibilityByID = `-- name: GetWorkflowVersionInputSchemaCompatibilityByID :one
SELECT id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_version_input_schema_compatibility"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowVersionInputSchemaCompatibilityByID(ctx context.Context, id int32) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionInputSchemaCompatibilityByID, id)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hasCompatibilityHistoricalRun = `-- name: HasCompatibilityHistoricalRun :one
SELECT EXISTS (
    SELECT 1
    FROM "workflow_version_input_schema_compatibility" c
    JOIN "workflow_run" wr ON wr.workflow_version_id = c.workflow_version_id
    JOIN "message" m ON m.id = wr.message_id AND m.workflow_input_schema_id = c.workflow_input_schema_id
    WHERE c.id = $1
) AS has_run
`

func (q *Queries) HasCompatibilityHistoricalRun(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompatibilityHistoricalRun, id)
	var has_run bool
	err := row.Scan(&has_run)
	return has_run, err
}

const listActiveRoutingCompatibilitiesByInputSchemaID = `-- name: ListActiveRoutingCompatibilitiesByInputSchemaID :many
SELECT
    c.id,
    c.workflow_version_id,
    c.workflow_input_schema_id,
    c.compatibility_type,
    c.workflow_input_mapper_id,
    c.default_values,
    c.is_default_route,
    v.workflow_id,
    v.version_number,
    v.name AS workflow_version_name,
    v.is_valid,
    v.is_active,
    v.archived_at
FROM "workflow_version_input_schema_compatibility" c
JOIN "workflow_version" v ON v.id = c.workflow_version_id
WHERE c.workflow_input_schema_id = $1
  AND c.is_active = TRUE
  AND c.deleted_at IS NULL
  AND v.deleted_at IS NULL
  AND v.archived_at IS NULL
  AND v.is_active = TRUE
  AND v.is_valid = TRUE
ORDER BY c.is_default_route DESC, v.version_number DESC, v.id DESC
`

type ListActiveRoutingCompatibilitiesByInputSchemaIDRow struct {
	ID                    int32            `json:"id"`
	WorkflowVersionID     int32            `json:"workflow_version_id"`
	WorkflowInputSchemaID int32            `json:"workflow_input_schema_id"`
	CompatibilityType     string           `json:"compatibility_type"`
	WorkflowInputMapperID pgtype.Int4      `json:"workflow_input_mapper_id"`
	DefaultValues         []byte           `json:"default_values"`
	IsDefaultRoute        bool             `json:"is_default_route"`
	WorkflowID            int32            `json:"workflow_id"`
	VersionNumber         int32            `json:"version_number"`
	WorkflowVersionName   pgtype.Text      `json:"workflow_version_name"`
	IsValid               bool             `json:"is_valid"`
	IsActive              bool             `json:"is_active"`
	ArchivedAt            pgtype.Timestamp `json:"archived_at"`
}

func (q *Queries) ListActiveRoutingCompatibilitiesByInputSchemaID(ctx context.Context, workflowInputSchemaID int32) ([]ListActiveRoutingCompatibilitiesByInputSchemaIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoutingCompatibilitiesByInputSchemaID, workflowInputSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRoutingCompatibilitiesByInputSchemaIDRow
	for rows.Next() {
		var i ListActiveRoutingCompatibilitiesByInputSchemaIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.WorkflowInputSchemaID,
			&i.CompatibilityType,
			&i.WorkflowInputMapperID,
			&i.DefaultValues,
			&i.IsDefaultRoute,
			&i.WorkflowID,
			&i.VersionNumber,
			&i.WorkflowVersionName,
			&i.IsValid,
			&i.IsActive,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompatibilitiesByInputSchemaID = `-- name: ListCompatibilitiesByInputSchemaID :many
SELECT id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_version_input_schema_compatibility"
WHERE workflow_input_schema_id = $1 AND deleted_at IS NULL
ORDER BY is_default_route DESC, workflow_version_id, id
`

func (q *Queries) ListCompatibilitiesByInputSchemaID(ctx context.Context, workflowInputSchemaID int32) ([]WorkflowVersionInputSchemaCompatibility, error) {
	rows, err := q.db.Query(ctx, listCompatibilitiesByInputSchemaID, workflowInputSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersionInputSchemaCompatibility
	for rows.Next() {
		var i WorkflowVersionInputSchemaCompatibility
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.WorkflowInputSchemaID,
			&i.CompatibilityType,
			&i.WorkflowInputMapperID,
			&i.DefaultValues,
			&i.IsActive,
			&i.IsDefaultRoute,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompatibilitiesByVersionID = `-- name: ListCompatibilitiesByVersionID :many
SELECT id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_version_input_schema_compatibility"
WHERE workflow_version_id = $1 AND deleted_at IS NULL
ORDER BY is_default_route DESC, workflow_input_schema_id, id
`

func (q *Queries) ListCompatibilitiesByVersionID(ctx context.Context, workflowVersionID int32) ([]WorkflowVersionInputSchemaCompatibility, error) {
	rows, err := q.db.Query(ctx, listCompatibilitiesByVersionID, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersionInputSchemaCompatibility
	for rows.Next() {
		var i WorkflowVersionInputSchemaCompatibility
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.WorkflowInputSchemaID,
			&i.CompatibilityType,
			&i.WorkflowInputMapperID,
			&i.DefaultValues,
			&i.IsActive,
			&i.IsDefaultRoute,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompatibilitiesByWorkflowID = `-- name: ListCompatibilitiesByWorkflowID :many
SELECT c.id, c.workflow_version_id, c.workflow_input_schema_id, c.compatibility_type, c.workflow_input_mapper_id, c.default_values, c.is_active, c.is_default_route, c.created_by_user_id, c.updated_by_user_id, c.created_at, c.updated_at, c.deleted_at
FROM "workflow_version_input_schema_compatibility" c
JOIN "workflow_version" v ON v.id = c.workflow_version_id
WHERE v.workflow_id = $1
  AND c.deleted_at IS NULL
  AND v.deleted_at IS NULL
ORDER BY c.workflow_input_schema_id, v.version_number, c.id
`

func (q *Queries) ListCompatibilitiesByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowVersionInputSchemaCompatibility, error) {
	rows, err := q.db.Query(ctx, listCompatibilitiesByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersionInputSchemaCompatibility
	for rows.Next() {
		var i WorkflowVersionInputSchemaCompatibility
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.WorkflowInputSchemaID,
			&i.CompatibilityType,
			&i.WorkflowInputMapperID,
			&i.DefaultValues,
			&i.IsActive,
			&i.IsDefaultRoute,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowVersionInputSchemaCompatibility = `-- name: SoftDeleteWorkflowVersionInputSchemaCompatibility :exec
UPDATE "workflow_version_input_schema_compatibility"
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowVersionInputSchemaCompatibility(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowVersionInputSchemaCompatibility, id)
	return err
}

const updateCompatibilityDefaultRoute = `-- name: UpdateCompatibilityDefaultRoute :one
UPDATE "workflow_version_input_schema_compatibility"
SET is_default_route = $2,
    updated_by_user_id = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type UpdateCompatibilityDefaultRouteParams struct {
	ID              int32       `json:"id"`
	IsDefaultRoute  bool        `json:"is_default_route"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) UpdateCompatibilityDefaultRoute(ctx context.Context, arg UpdateCompatibilityDefaultRouteParams) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, updateCompatibilityDefaultRoute, arg.ID, arg.IsDefaultRoute, arg.UpdatedByUserID)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowVersionInputSchemaCompatibility = `-- name: UpdateWorkflowVersionInputSchemaCompatibility :one
UPDATE "workflow_version_input_schema_compatibility"
SET compatibility_type = $2,
    workflow_input_mapper_id = $3,
    default_values = $4,
    is_active = $5,
    is_default_route = $6,
    updated_by_user_id = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_version_id, workflow_input_schema_id, compatibility_type, workflow_input_mapper_id, default_values, is_active, is_default_route, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type UpdateWorkflowVersionInputSchemaCompatibilityParams struct {
	ID                    int32       `json:"id"`
	CompatibilityType     string      `json:"compatibility_type"`
	WorkflowInputMapperID pgtype.Int4 `json:"workflow_input_mapper_id"`
	DefaultValues         []byte      `json:"default_values"`
	IsActive              bool        `json:"is_active"`
	IsDefaultRoute        bool        `json:"is_default_route"`
	UpdatedByUserID       pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) UpdateWorkflowVersionInputSchemaCompatibility(ctx context.Context, arg UpdateWorkflowVersionInputSchemaCompatibilityParams) (WorkflowVersionInputSchemaCompatibility, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionInputSchemaCompatibility,
		arg.ID,
		arg.CompatibilityType,
		arg.WorkflowInputMapperID,
		arg.DefaultValues,
		arg.IsActive,
		arg.IsDefaultRoute,
		arg.UpdatedByUserID,
	)
	var i WorkflowVersionInputSchemaCompatibility
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.WorkflowInputSchemaID,
		&i.CompatibilityType,
		&i.WorkflowInputMapperID,
		&i.DefaultValues,
		&i.IsActive,
		&i.IsDefaultRoute,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
