// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_step.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowStep = `-- name: CreateWorkflowStep :one
INSERT INTO "workflow_step" (workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, canvas_position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, canvas_position, created_at, updated_at, deleted_at
`

type CreateWorkflowStepParams struct {
	WorkflowVersionID        int32       `json:"workflow_version_id"`
	StepType                 string      `json:"step_type"`
	WorkTypeID               pgtype.Int4 `json:"work_type_id"`
	WorkerSettingsRevisionID pgtype.Int4 `json:"worker_settings_revision_id"`
	ControlKind              pgtype.Text `json:"control_kind"`
	ControlSettings          []byte      `json:"control_settings"`
	InputMapping             []byte      `json:"input_mapping"`
	CanvasPosition           []byte      `json:"canvas_position"`
}

func (q *Queries) CreateWorkflowStep(ctx context.Context, arg CreateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRow(ctx, createWorkflowStep,
		arg.WorkflowVersionID,
		arg.StepType,
		arg.WorkTypeID,
		arg.WorkerSettingsRevisionID,
		arg.ControlKind,
		arg.ControlSettings,
		arg.InputMapping,
		arg.CanvasPosition,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.StepType,
		&i.WorkTypeID,
		&i.WorkerSettingsRevisionID,
		&i.ControlKind,
		&i.ControlSettings,
		&i.InputMapping,
		&i.CanvasPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteWorkflowStepsByVersionID = `-- name: DeleteWorkflowStepsByVersionID :exec
UPDATE "workflow_step"
SET deleted_at = CURRENT_TIMESTAMP
WHERE workflow_version_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteWorkflowStepsByVersionID(ctx context.Context, workflowVersionID int32) error {
	_, err := q.db.Exec(ctx, deleteWorkflowStepsByVersionID, workflowVersionID)
	return err
}

const getWorkflowStepByID = `-- name: GetWorkflowStepByID :one
SELECT id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, canvas_position, created_at, updated_at, deleted_at FROM "workflow_step"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowStepByID(ctx context.Context, id int32) (WorkflowStep, error) {
	row := q.db.QueryRow(ctx, getWorkflowStepByID, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.StepType,
		&i.WorkTypeID,
		&i.WorkerSettingsRevisionID,
		&i.ControlKind,
		&i.ControlSettings,
		&i.InputMapping,
		&i.CanvasPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEnrichedStepsByVersionID = `-- name: ListEnrichedStepsByVersionID :many
SELECT
    ws.id, ws.workflow_version_id, ws.step_type, ws.work_type_id, ws.worker_settings_revision_id, ws.control_kind, ws.control_settings, ws.input_mapping, ws.canvas_position, ws.created_at, ws.updated_at, ws.deleted_at,
    wt.name AS work_type_name,
    wt.code AS work_type_code,
    wt.meta AS work_type_meta,
    wsr.settings_data AS config,
    wss.settings_schema,
    wss.input_schema,
    wss.output_schema
FROM "workflow_step" ws
LEFT JOIN "work_type" wt ON wt.id = ws.work_type_id
LEFT JOIN "worker_settings_revision" wsr ON wsr.id = ws.worker_settings_revision_id
LEFT JOIN "worker_settings_schema" wss ON wss.id = wsr.worker_settings_schema_id
WHERE ws.workflow_version_id = $1 AND ws.deleted_at IS NULL
ORDER BY ws.id
`

type ListEnrichedStepsByVersionIDRow struct {
	ID                       int32            `json:"id"`
	WorkflowVersionID        int32            `json:"workflow_version_id"`
	StepType                 string           `json:"step_type"`
	WorkTypeID               pgtype.Int4      `json:"work_type_id"`
	WorkerSettingsRevisionID pgtype.Int4      `json:"worker_settings_revision_id"`
	ControlKind              pgtype.Text      `json:"control_kind"`
	ControlSettings          []byte           `json:"control_settings"`
	InputMapping             []byte           `json:"input_mapping"`
	CanvasPosition           []byte           `json:"canvas_position"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
	DeletedAt                pgtype.Timestamp `json:"deleted_at"`
	WorkTypeName             pgtype.Text      `json:"work_type_name"`
	WorkTypeCode             pgtype.Text      `json:"work_type_code"`
	WorkTypeMeta             []byte           `json:"work_type_meta"`
	Config                   []byte           `json:"config"`
	SettingsSchema           []byte           `json:"settings_schema"`
	InputSchema              []byte           `json:"input_schema"`
	OutputSchema             []byte           `json:"output_schema"`
}

func (q *Queries) ListEnrichedStepsByVersionID(ctx context.Context, workflowVersionID int32) ([]ListEnrichedStepsByVersionIDRow, error) {
	rows, err := q.db.Query(ctx, listEnrichedStepsByVersionID, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrichedStepsByVersionIDRow
	for rows.Next() {
		var i ListEnrichedStepsByVersionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.StepType,
			&i.WorkTypeID,
			&i.WorkerSettingsRevisionID,
			&i.ControlKind,
			&i.ControlSettings,
			&i.InputMapping,
			&i.CanvasPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.WorkTypeName,
			&i.WorkTypeCode,
			&i.WorkTypeMeta,
			&i.Config,
			&i.SettingsSchema,
			&i.InputSchema,
			&i.OutputSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepsByVersionID = `-- name: ListWorkflowStepsByVersionID :many
SELECT id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, canvas_position, created_at, updated_at, deleted_at FROM "workflow_step"
WHERE workflow_version_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListWorkflowStepsByVersionID(ctx context.Context, workflowVersionID int32) ([]WorkflowStep, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepsByVersionID, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStep
	for rows.Next() {
		var i WorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.StepType,
			&i.WorkTypeID,
			&i.WorkerSettingsRevisionID,
			&i.ControlKind,
			&i.ControlSettings,
			&i.InputMapping,
			&i.CanvasPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowStep = `-- name: SoftDeleteWorkflowStep :exec
UPDATE "workflow_step"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowStep(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowStep, id)
	return err
}

const updateWorkflowStep = `-- name: UpdateWorkflowStep :one
UPDATE "workflow_step"
SET step_type = $2,
    work_type_id = $3,
    worker_settings_revision_id = $4,
    control_kind = $5,
    control_settings = $6,
    input_mapping = $7,
    canvas_position = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, canvas_position, created_at, updated_at, deleted_at
`

type UpdateWorkflowStepParams struct {
	ID                       int32       `json:"id"`
	StepType                 string      `json:"step_type"`
	WorkTypeID               pgtype.Int4 `json:"work_type_id"`
	WorkerSettingsRevisionID pgtype.Int4 `json:"worker_settings_revision_id"`
	ControlKind              pgtype.Text `json:"control_kind"`
	ControlSettings          []byte      `json:"control_settings"`
	InputMapping             []byte      `json:"input_mapping"`
	CanvasPosition           []byte      `json:"canvas_position"`
}

func (q *Queries) UpdateWorkflowStep(ctx context.Context, arg UpdateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRow(ctx, updateWorkflowStep,
		arg.ID,
		arg.StepType,
		arg.WorkTypeID,
		arg.WorkerSettingsRevisionID,
		arg.ControlKind,
		arg.ControlSettings,
		arg.InputMapping,
		arg.CanvasPosition,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.StepType,
		&i.WorkTypeID,
		&i.WorkerSettingsRevisionID,
		&i.ControlKind,
		&i.ControlSettings,
		&i.InputMapping,
		&i.CanvasPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowStepPosition = `-- name: UpdateWorkflowStepPosition :exec
UPDATE "workflow_step"
SET canvas_position = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateWorkflowStepPositionParams struct {
	ID             int32  `json:"id"`
	CanvasPosition []byte `json:"canvas_position"`
}

func (q *Queries) UpdateWorkflowStepPosition(ctx context.Context, arg UpdateWorkflowStepPositionParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowStepPosition, arg.ID, arg.CanvasPosition)
	return err
}
