// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker.sql

package db

import (
	"context"
)

const createNewWorker = `-- name: CreateNewWorker :one
INSERT INTO "worker" (work_type_id, worker_settings_schema_id, "name", metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, work_type_id, worker_settings_schema_id, name, metadata, registered_at, last_heartbeat_at
`

type CreateNewWorkerParams struct {
	WorkTypeID             int32  `json:"work_type_id"`
	WorkerSettingsSchemaID int32  `json:"worker_settings_schema_id"`
	Name                   string `json:"name"`
	Metadata               []byte `json:"metadata"`
}

func (q *Queries) CreateNewWorker(ctx context.Context, arg CreateNewWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createNewWorker,
		arg.WorkTypeID,
		arg.WorkerSettingsSchemaID,
		arg.Name,
		arg.Metadata,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.WorkerSettingsSchemaID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM "worker"
WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getNewWorkerByID = `-- name: GetNewWorkerByID :one
SELECT id, work_type_id, worker_settings_schema_id, name, metadata, registered_at, last_heartbeat_at FROM "worker"
WHERE id = $1
`

func (q *Queries) GetNewWorkerByID(ctx context.Context, id int32) (Worker, error) {
	row := q.db.QueryRow(ctx, getNewWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.WorkerSettingsSchemaID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const getWorkerByWorkTypeAndName = `-- name: GetWorkerByWorkTypeAndName :one
SELECT id, work_type_id, worker_settings_schema_id, name, metadata, registered_at, last_heartbeat_at FROM "worker"
WHERE work_type_id = $1 AND "name" = $2
LIMIT 1
`

type GetWorkerByWorkTypeAndNameParams struct {
	WorkTypeID int32  `json:"work_type_id"`
	Name       string `json:"name"`
}

func (q *Queries) GetWorkerByWorkTypeAndName(ctx context.Context, arg GetWorkerByWorkTypeAndNameParams) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByWorkTypeAndName, arg.WorkTypeID, arg.Name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.WorkerSettingsSchemaID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const listNewWorkersByWorkTypeID = `-- name: ListNewWorkersByWorkTypeID :many
SELECT id, work_type_id, worker_settings_schema_id, name, metadata, registered_at, last_heartbeat_at FROM "worker"
WHERE work_type_id = $1
ORDER BY id
`

func (q *Queries) ListNewWorkersByWorkTypeID(ctx context.Context, workTypeID int32) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listNewWorkersByWorkTypeID, workTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.WorkTypeID,
			&i.WorkerSettingsSchemaID,
			&i.Name,
			&i.Metadata,
			&i.RegisteredAt,
			&i.LastHeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowUsagesByWorkerID = `-- name: ListWorkflowUsagesByWorkerID :many
SELECT DISTINCT
    w.id AS workflow_id,
    w.name AS workflow_name,
    w.system_id AS system_id,
    wv.id AS workflow_version_id,
    wv.version_number AS workflow_version_number
FROM "worker" worker_row
JOIN "worker_settings_revision" wsr
    ON wsr.worker_settings_schema_id = worker_row.worker_settings_schema_id
JOIN "workflow_step" ws
    ON ws.worker_settings_revision_id = wsr.id
    AND ws.deleted_at IS NULL
JOIN "workflow_version" wv
    ON wv.id = ws.workflow_version_id
    AND wv.deleted_at IS NULL
JOIN "workflow" w
    ON w.id = wv.workflow_id
    AND w.deleted_at IS NULL
WHERE worker_row.id = $1
ORDER BY w.id, wv.version_number
`

type ListWorkflowUsagesByWorkerIDRow struct {
	WorkflowID            int32  `json:"workflow_id"`
	WorkflowName          string `json:"workflow_name"`
	SystemID              int32  `json:"system_id"`
	WorkflowVersionID     int32  `json:"workflow_version_id"`
	WorkflowVersionNumber int32  `json:"workflow_version_number"`
}

func (q *Queries) ListWorkflowUsagesByWorkerID(ctx context.Context, id int32) ([]ListWorkflowUsagesByWorkerIDRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowUsagesByWorkerID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowUsagesByWorkerIDRow
	for rows.Next() {
		var i ListWorkflowUsagesByWorkerIDRow
		if err := rows.Scan(
			&i.WorkflowID,
			&i.WorkflowName,
			&i.SystemID,
			&i.WorkflowVersionID,
			&i.WorkflowVersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNewWorkerHeartbeat = `-- name: UpdateNewWorkerHeartbeat :exec
UPDATE "worker"
SET last_heartbeat_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateNewWorkerHeartbeat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateNewWorkerHeartbeat, id)
	return err
}

const updateNewWorkerSchema = `-- name: UpdateNewWorkerSchema :one
UPDATE "worker"
SET worker_settings_schema_id = $2
WHERE id = $1
RETURNING id, work_type_id, worker_settings_schema_id, name, metadata, registered_at, last_heartbeat_at
`

type UpdateNewWorkerSchemaParams struct {
	ID                     int32 `json:"id"`
	WorkerSettingsSchemaID int32 `json:"worker_settings_schema_id"`
}

func (q *Queries) UpdateNewWorkerSchema(ctx context.Context, arg UpdateNewWorkerSchemaParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateNewWorkerSchema, arg.ID, arg.WorkerSettingsSchemaID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.WorkerSettingsSchemaID,
		&i.Name,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}
