// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO "workflow" (system_id, "name", priority, input_validation, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, system_id, name, priority, input_validation, description, created_at, updated_at, deleted_at
`

type CreateWorkflowParams struct {
	SystemID        int32                 `json:"system_id"`
	Name            string                `json:"name"`
	Priority        int32                 `json:"priority"`
	InputValidation pqtype.NullRawMessage `json:"input_validation"`
	Description     sql.NullString        `json:"description"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.SystemID,
		arg.Name,
		arg.Priority,
		arg.InputValidation,
		arg.Description,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.Priority,
		&i.InputValidation,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, system_id, name, priority, input_validation, description, created_at, updated_at, deleted_at FROM "workflow"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id int32) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.Priority,
		&i.InputValidation,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkflowsBySystemID = `-- name: ListWorkflowsBySystemID :many
SELECT id, system_id, name, priority, input_validation, description, created_at, updated_at, deleted_at FROM "workflow"
WHERE system_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListWorkflowsBySystemID(ctx context.Context, systemID int32) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowsBySystemID, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Name,
			&i.Priority,
			&i.InputValidation,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflow = `-- name: SoftDeleteWorkflow :exec
UPDATE "workflow"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflow(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteWorkflow, id)
	return err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE "workflow"
SET "name" = $2, priority = $3, description = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, system_id, name, priority, input_validation, description, created_at, updated_at, deleted_at
`

type UpdateWorkflowParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Priority    int32          `json:"priority"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Priority,
		arg.Description,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.Priority,
		&i.InputValidation,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowInputValidation = `-- name: UpdateWorkflowInputValidation :one
UPDATE "workflow"
SET input_validation = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, system_id, name, priority, input_validation, description, created_at, updated_at, deleted_at
`

type UpdateWorkflowInputValidationParams struct {
	ID              int32                 `json:"id"`
	InputValidation pqtype.NullRawMessage `json:"input_validation"`
}

func (q *Queries) UpdateWorkflowInputValidation(ctx context.Context, arg UpdateWorkflowInputValidationParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowInputValidation, arg.ID, arg.InputValidation)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.Priority,
		&i.InputValidation,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
