// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker_settings_revision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cloneWorkerSettingsRevision = `-- name: CloneWorkerSettingsRevision :one
INSERT INTO "worker_settings_revision" (worker_settings_schema_id, created_by_user_id, settings_data)
SELECT worker_settings_schema_id, $2, settings_data
FROM "worker_settings_revision"
WHERE id = $1
RETURNING id, worker_settings_schema_id, created_by_user_id, settings_data, created_at
`

type CloneWorkerSettingsRevisionParams struct {
	Column1 pgtype.Int4 `json:"column_1"`
	Column2 pgtype.Int4 `json:"column_2"`
}

func (q *Queries) CloneWorkerSettingsRevision(ctx context.Context, arg CloneWorkerSettingsRevisionParams) (WorkerSettingsRevision, error) {
	row := q.db.QueryRow(ctx, cloneWorkerSettingsRevision, arg.Column1, arg.Column2)
	var i WorkerSettingsRevision
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsSchemaID,
		&i.CreatedByUserID,
		&i.SettingsData,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkerSettingsRevision = `-- name: CreateWorkerSettingsRevision :one
INSERT INTO "worker_settings_revision" (worker_settings_schema_id, created_by_user_id, settings_data)
VALUES ($1, $2, $3)
RETURNING id, worker_settings_schema_id, created_by_user_id, settings_data, created_at
`

type CreateWorkerSettingsRevisionParams struct {
	WorkerSettingsSchemaID int32       `json:"worker_settings_schema_id"`
	CreatedByUserID        pgtype.Int4 `json:"created_by_user_id"`
	SettingsData           []byte      `json:"settings_data"`
}

func (q *Queries) CreateWorkerSettingsRevision(ctx context.Context, arg CreateWorkerSettingsRevisionParams) (WorkerSettingsRevision, error) {
	row := q.db.QueryRow(ctx, createWorkerSettingsRevision, arg.WorkerSettingsSchemaID, arg.CreatedByUserID, arg.SettingsData)
	var i WorkerSettingsRevision
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsSchemaID,
		&i.CreatedByUserID,
		&i.SettingsData,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkerSettingsRevisionByID = `-- name: GetWorkerSettingsRevisionByID :one
SELECT id, worker_settings_schema_id, created_by_user_id, settings_data, created_at FROM "worker_settings_revision"
WHERE id = $1
`

func (q *Queries) GetWorkerSettingsRevisionByID(ctx context.Context, id int32) (WorkerSettingsRevision, error) {
	row := q.db.QueryRow(ctx, getWorkerSettingsRevisionByID, id)
	var i WorkerSettingsRevision
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsSchemaID,
		&i.CreatedByUserID,
		&i.SettingsData,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkerSettingsRevisionsBySchemaID = `-- name: ListWorkerSettingsRevisionsBySchemaID :many
SELECT id, worker_settings_schema_id, created_by_user_id, settings_data, created_at FROM "worker_settings_revision"
WHERE worker_settings_schema_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkerSettingsRevisionsBySchemaID(ctx context.Context, workerSettingsSchemaID int32) ([]WorkerSettingsRevision, error) {
	rows, err := q.db.Query(ctx, listWorkerSettingsRevisionsBySchemaID, workerSettingsSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerSettingsRevision
	for rows.Next() {
		var i WorkerSettingsRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkerSettingsSchemaID,
			&i.CreatedByUserID,
			&i.SettingsData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkerSettingsRevisionSettings = `-- name: UpdateWorkerSettingsRevisionSettings :one
UPDATE "worker_settings_revision"
SET settings_data = $2
WHERE id = $1
RETURNING id, worker_settings_schema_id, created_by_user_id, settings_data, created_at
`

type UpdateWorkerSettingsRevisionSettingsParams struct {
	ID           int32  `json:"id"`
	SettingsData []byte `json:"settings_data"`
}

func (q *Queries) UpdateWorkerSettingsRevisionSettings(ctx context.Context, arg UpdateWorkerSettingsRevisionSettingsParams) (WorkerSettingsRevision, error) {
	row := q.db.QueryRow(ctx, updateWorkerSettingsRevisionSettings, arg.ID, arg.SettingsData)
	var i WorkerSettingsRevision
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsSchemaID,
		&i.CreatedByUserID,
		&i.SettingsData,
		&i.CreatedAt,
	)
	return i, err
}
