// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_version.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveWorkflowVersion = `-- name: ArchiveWorkflowVersion :one
UPDATE "workflow_version"
SET archived_at = COALESCE(archived_at, CURRENT_TIMESTAMP),
    is_active = FALSE,
    updated_by_user_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type ArchiveWorkflowVersionParams struct {
	ID              int32       `json:"id"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) ArchiveWorkflowVersion(ctx context.Context, arg ArchiveWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, archiveWorkflowVersion, arg.ID, arg.UpdatedByUserID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO "workflow_version" (workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, is_control_group)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type CreateWorkflowVersionParams struct {
	WorkflowID      int32       `json:"workflow_id"`
	CreatedByUserID pgtype.Int4 `json:"created_by_user_id"`
	VersionNumber   int32       `json:"version_number"`
	Name            pgtype.Text `json:"name"`
	IsValid         bool        `json:"is_valid"`
	IsActive        bool        `json:"is_active"`
	TrafficWeight   int32       `json:"traffic_weight"`
	IsControlGroup  bool        `json:"is_control_group"`
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion,
		arg.WorkflowID,
		arg.CreatedByUserID,
		arg.VersionNumber,
		arg.Name,
		arg.IsValid,
		arg.IsActive,
		arg.TrafficWeight,
		arg.IsControlGroup,
	)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const getMaxVersionNumberByWorkflowID = `-- name: GetMaxVersionNumberByWorkflowID :one
SELECT COALESCE(MAX(version_number), 0)::int FROM "workflow_version"
WHERE workflow_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMaxVersionNumberByWorkflowID(ctx context.Context, workflowID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxVersionNumberByWorkflowID, workflowID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getWorkflowVersionByID = `-- name: GetWorkflowVersionByID :one
SELECT id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id FROM "workflow_version"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowVersionByID(ctx context.Context, id int32) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersionByID, id)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const invalidateWorkflowVersionsByWorkflowID = `-- name: InvalidateWorkflowVersionsByWorkflowID :exec
UPDATE "workflow_version"
SET is_valid = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE workflow_id = $1 AND deleted_at IS NULL
`

func (q *Queries) InvalidateWorkflowVersionsByWorkflowID(ctx context.Context, workflowID int32) error {
	_, err := q.db.Exec(ctx, invalidateWorkflowVersionsByWorkflowID, workflowID)
	return err
}

const isWorkflowVersionReferenced = `-- name: IsWorkflowVersionReferenced :one
SELECT EXISTS (
    SELECT 1 FROM "workflow_run" wr WHERE wr.workflow_version_id = $1
    UNION ALL
    SELECT 1 FROM "workflow_experiment_variant" ev WHERE ev.workflow_version_id = $1 AND ev.deleted_at IS NULL
    UNION ALL
    SELECT 1 FROM "workflow_version_input_schema_compatibility" c WHERE c.workflow_version_id = $1 AND c.deleted_at IS NULL
) AS is_referenced
`

func (q *Queries) IsWorkflowVersionReferenced(ctx context.Context, workflowVersionID int32) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkflowVersionReferenced, workflowVersionID)
	var is_referenced bool
	err := row.Scan(&is_referenced)
	return is_referenced, err
}

const listActiveWorkflowVersions = `-- name: ListActiveWorkflowVersions :many
SELECT id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id FROM "workflow_version"
WHERE workflow_id = $1 AND is_active = TRUE AND deleted_at IS NULL AND archived_at IS NULL
ORDER BY version_number
`

func (q *Queries) ListActiveWorkflowVersions(ctx context.Context, workflowID int32) ([]WorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowVersions, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersion
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.CreatedByUserID,
			&i.VersionNumber,
			&i.Name,
			&i.IsValid,
			&i.IsActive,
			&i.TrafficWeight,
			&i.TrafficUpdatedAt,
			&i.IsControlGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LockedAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.UpdatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkflowVersionsByWorkflowID = `-- name: ListAllWorkflowVersionsByWorkflowID :many
SELECT id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id FROM "workflow_version"
WHERE workflow_id = $1
ORDER BY version_number
`

func (q *Queries) ListAllWorkflowVersionsByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listAllWorkflowVersionsByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersion
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.CreatedByUserID,
			&i.VersionNumber,
			&i.Name,
			&i.IsValid,
			&i.IsActive,
			&i.TrafficWeight,
			&i.TrafficUpdatedAt,
			&i.IsControlGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LockedAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.UpdatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTrafficCandidatesByWorkflowID = `-- name: ListWorkflowTrafficCandidatesByWorkflowID :many
SELECT
    wv.id,
    wv.workflow_id,
    wv.version_number,
    wv.is_active,
    wv.traffic_weight,
    wv.deleted_at,
    COUNT(msg.id)::bigint AS run_count
FROM "workflow_version" wv
LEFT JOIN "workflow_run" wr ON wr.workflow_version_id = wv.id
LEFT JOIN "message" msg
    ON msg.id = wr.message_id
    AND msg.created_at >= wv.traffic_updated_at
WHERE wv.workflow_id = $1
GROUP BY wv.id
ORDER BY wv.is_active DESC, wv.version_number DESC
`

type ListWorkflowTrafficCandidatesByWorkflowIDRow struct {
	ID            int32            `json:"id"`
	WorkflowID    int32            `json:"workflow_id"`
	VersionNumber int32            `json:"version_number"`
	IsActive      bool             `json:"is_active"`
	TrafficWeight int32            `json:"traffic_weight"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	RunCount      int64            `json:"run_count"`
}

func (q *Queries) ListWorkflowTrafficCandidatesByWorkflowID(ctx context.Context, workflowID int32) ([]ListWorkflowTrafficCandidatesByWorkflowIDRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowTrafficCandidatesByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowTrafficCandidatesByWorkflowIDRow
	for rows.Next() {
		var i ListWorkflowTrafficCandidatesByWorkflowIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.VersionNumber,
			&i.IsActive,
			&i.TrafficWeight,
			&i.DeletedAt,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersionSummariesByWorkflowID = `-- name: ListWorkflowVersionSummariesByWorkflowID :many
SELECT
    wv.id,
    wv.workflow_id,
    COALESCE(wv.name, 'Version ' || wv.version_number::text) AS name,
    wv.version_number,
    wv.is_valid,
    wv.is_active,
    wv.traffic_weight,
    wv.is_control_group,
    wv.locked_at,
    wv.published_at,
    wv.archived_at,
    wv.created_at,
    wv.updated_at,
    wv.deleted_at,
    COUNT(DISTINCT wr.id)::bigint AS run_count,
    COUNT(DISTINCT c.workflow_input_schema_id)::bigint AS compatible_schema_count
FROM "workflow_version" wv
LEFT JOIN "workflow_run" wr ON wr.workflow_version_id = wv.id
LEFT JOIN "workflow_version_input_schema_compatibility" c
    ON c.workflow_version_id = wv.id
    AND c.is_active = TRUE
    AND c.deleted_at IS NULL
WHERE wv.workflow_id = $1
GROUP BY wv.id
ORDER BY wv.is_active DESC, wv.version_number DESC
`

type ListWorkflowVersionSummariesByWorkflowIDRow struct {
	ID                    int32            `json:"id"`
	WorkflowID            int32            `json:"workflow_id"`
	Name                  pgtype.Text      `json:"name"`
	VersionNumber         int32            `json:"version_number"`
	IsValid               bool             `json:"is_valid"`
	IsActive              bool             `json:"is_active"`
	TrafficWeight         int32            `json:"traffic_weight"`
	IsControlGroup        bool             `json:"is_control_group"`
	LockedAt              pgtype.Timestamp `json:"locked_at"`
	PublishedAt           pgtype.Timestamp `json:"published_at"`
	ArchivedAt            pgtype.Timestamp `json:"archived_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
	RunCount              int64            `json:"run_count"`
	CompatibleSchemaCount int64            `json:"compatible_schema_count"`
}

func (q *Queries) ListWorkflowVersionSummariesByWorkflowID(ctx context.Context, workflowID int32) ([]ListWorkflowVersionSummariesByWorkflowIDRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersionSummariesByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowVersionSummariesByWorkflowIDRow
	for rows.Next() {
		var i ListWorkflowVersionSummariesByWorkflowIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Name,
			&i.VersionNumber,
			&i.IsValid,
			&i.IsActive,
			&i.TrafficWeight,
			&i.IsControlGroup,
			&i.LockedAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RunCount,
			&i.CompatibleSchemaCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowVersionsByWorkflowID = `-- name: ListWorkflowVersionsByWorkflowID :many
SELECT id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id FROM "workflow_version"
WHERE workflow_id = $1 AND deleted_at IS NULL
ORDER BY version_number
`

func (q *Queries) ListWorkflowVersionsByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listWorkflowVersionsByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowVersion
	for rows.Next() {
		var i WorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.CreatedByUserID,
			&i.VersionNumber,
			&i.Name,
			&i.IsValid,
			&i.IsActive,
			&i.TrafficWeight,
			&i.TrafficUpdatedAt,
			&i.IsControlGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LockedAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.UpdatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowVersion = `-- name: SoftDeleteWorkflowVersion :exec
UPDATE "workflow_version"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowVersion(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowVersion, id)
	return err
}

const updateWorkflowVersionActive = `-- name: UpdateWorkflowVersionActive :one
UPDATE "workflow_version"
SET is_active = $2,
    locked_at = CASE WHEN $2 THEN COALESCE(locked_at, CURRENT_TIMESTAMP) ELSE locked_at END,
    published_at = CASE WHEN $2 THEN COALESCE(published_at, CURRENT_TIMESTAMP) ELSE published_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type UpdateWorkflowVersionActiveParams struct {
	ID       int32 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateWorkflowVersionActive(ctx context.Context, arg UpdateWorkflowVersionActiveParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionActive, arg.ID, arg.IsActive)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const updateWorkflowVersionName = `-- name: UpdateWorkflowVersionName :one
UPDATE "workflow_version"
SET name = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type UpdateWorkflowVersionNameParams struct {
	ID   int32       `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateWorkflowVersionName(ctx context.Context, arg UpdateWorkflowVersionNameParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionName, arg.ID, arg.Name)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const updateWorkflowVersionTrafficWeight = `-- name: UpdateWorkflowVersionTrafficWeight :one
UPDATE "workflow_version"
SET traffic_weight = $2, traffic_updated_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type UpdateWorkflowVersionTrafficWeightParams struct {
	ID            int32 `json:"id"`
	TrafficWeight int32 `json:"traffic_weight"`
}

func (q *Queries) UpdateWorkflowVersionTrafficWeight(ctx context.Context, arg UpdateWorkflowVersionTrafficWeightParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionTrafficWeight, arg.ID, arg.TrafficWeight)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const updateWorkflowVersionTrafficWeightIncludingDeleted = `-- name: UpdateWorkflowVersionTrafficWeightIncludingDeleted :one
UPDATE "workflow_version"
SET traffic_weight = $2, traffic_updated_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type UpdateWorkflowVersionTrafficWeightIncludingDeletedParams struct {
	ID            int32 `json:"id"`
	TrafficWeight int32 `json:"traffic_weight"`
}

func (q *Queries) UpdateWorkflowVersionTrafficWeightIncludingDeleted(ctx context.Context, arg UpdateWorkflowVersionTrafficWeightIncludingDeletedParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionTrafficWeightIncludingDeleted, arg.ID, arg.TrafficWeight)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const updateWorkflowVersionValid = `-- name: UpdateWorkflowVersionValid :one
UPDATE "workflow_version"
SET is_valid = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, created_by_user_id, version_number, name, is_valid, is_active, traffic_weight, traffic_updated_at, is_control_group, created_at, updated_at, deleted_at, locked_at, published_at, archived_at, updated_by_user_id
`

type UpdateWorkflowVersionValidParams struct {
	ID      int32 `json:"id"`
	IsValid bool  `json:"is_valid"`
}

func (q *Queries) UpdateWorkflowVersionValid(ctx context.Context, arg UpdateWorkflowVersionValidParams) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, updateWorkflowVersionValid, arg.ID, arg.IsValid)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.CreatedByUserID,
		&i.VersionNumber,
		&i.Name,
		&i.IsValid,
		&i.IsActive,
		&i.TrafficWeight,
		&i.TrafficUpdatedAt,
		&i.IsControlGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}
