// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_input_mapper.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowInputMapper = `-- name: CreateWorkflowInputMapper :one
INSERT INTO "workflow_input_mapper" (workflow_id, name, mapper_type, rules, is_active, created_by_user_id, updated_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workflow_id, name, mapper_type, rules, is_active, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type CreateWorkflowInputMapperParams struct {
	WorkflowID      int32       `json:"workflow_id"`
	Name            string      `json:"name"`
	MapperType      string      `json:"mapper_type"`
	Rules           []byte      `json:"rules"`
	IsActive        bool        `json:"is_active"`
	CreatedByUserID pgtype.Int4 `json:"created_by_user_id"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) CreateWorkflowInputMapper(ctx context.Context, arg CreateWorkflowInputMapperParams) (WorkflowInputMapper, error) {
	row := q.db.QueryRow(ctx, createWorkflowInputMapper,
		arg.WorkflowID,
		arg.Name,
		arg.MapperType,
		arg.Rules,
		arg.IsActive,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i WorkflowInputMapper
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.MapperType,
		&i.Rules,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowInputMapperByID = `-- name: GetWorkflowInputMapperByID :one
SELECT id, workflow_id, name, mapper_type, rules, is_active, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_input_mapper"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowInputMapperByID(ctx context.Context, id int32) (WorkflowInputMapper, error) {
	row := q.db.QueryRow(ctx, getWorkflowInputMapperByID, id)
	var i WorkflowInputMapper
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.MapperType,
		&i.Rules,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkflowInputMappersByWorkflowID = `-- name: ListWorkflowInputMappersByWorkflowID :many
SELECT id, workflow_id, name, mapper_type, rules, is_active, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_input_mapper"
WHERE workflow_id = $1 AND deleted_at IS NULL
ORDER BY is_active DESC, name, id
`

func (q *Queries) ListWorkflowInputMappersByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowInputMapper, error) {
	rows, err := q.db.Query(ctx, listWorkflowInputMappersByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowInputMapper
	for rows.Next() {
		var i WorkflowInputMapper
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Name,
			&i.MapperType,
			&i.Rules,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowInputMapper = `-- name: SoftDeleteWorkflowInputMapper :exec
UPDATE "workflow_input_mapper"
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowInputMapper(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowInputMapper, id)
	return err
}

const updateWorkflowInputMapper = `-- name: UpdateWorkflowInputMapper :one
UPDATE "workflow_input_mapper"
SET name = $2,
    mapper_type = $3,
    rules = $4,
    is_active = $5,
    updated_by_user_id = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, name, mapper_type, rules, is_active, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type UpdateWorkflowInputMapperParams struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	MapperType      string      `json:"mapper_type"`
	Rules           []byte      `json:"rules"`
	IsActive        bool        `json:"is_active"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) UpdateWorkflowInputMapper(ctx context.Context, arg UpdateWorkflowInputMapperParams) (WorkflowInputMapper, error) {
	row := q.db.QueryRow(ctx, updateWorkflowInputMapper,
		arg.ID,
		arg.Name,
		arg.MapperType,
		arg.Rules,
		arg.IsActive,
		arg.UpdatedByUserID,
	)
	var i WorkflowInputMapper
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.MapperType,
		&i.Rules,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowInputMapperActive = `-- name: UpdateWorkflowInputMapperActive :one
UPDATE "workflow_input_mapper"
SET is_active = $2,
    updated_by_user_id = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, name, mapper_type, rules, is_active, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type UpdateWorkflowInputMapperActiveParams struct {
	ID              int32       `json:"id"`
	IsActive        bool        `json:"is_active"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) UpdateWorkflowInputMapperActive(ctx context.Context, arg UpdateWorkflowInputMapperActiveParams) (WorkflowInputMapper, error) {
	row := q.db.QueryRow(ctx, updateWorkflowInputMapperActive, arg.ID, arg.IsActive, arg.UpdatedByUserID)
	var i WorkflowInputMapper
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.MapperType,
		&i.Rules,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
