// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_input_schema.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultWorkflowInputSchema = `-- name: ClearDefaultWorkflowInputSchema :exec
UPDATE "workflow_input_schema"
SET is_default = FALSE,
    updated_by_user_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE workflow_id = $1 AND is_default = TRUE AND deleted_at IS NULL
`

type ClearDefaultWorkflowInputSchemaParams struct {
	WorkflowID      int32       `json:"workflow_id"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) ClearDefaultWorkflowInputSchema(ctx context.Context, arg ClearDefaultWorkflowInputSchemaParams) error {
	_, err := q.db.Exec(ctx, clearDefaultWorkflowInputSchema, arg.WorkflowID, arg.UpdatedByUserID)
	return err
}

const createWorkflowConfigurationAuditLog = `-- name: CreateWorkflowConfigurationAuditLog :one
INSERT INTO "workflow_configuration_audit_log" (entity_type, entity_id, action, actor_user_id, before_value, after_value)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entity_type, entity_id, action, actor_user_id, before_value, after_value, created_at
`

type CreateWorkflowConfigurationAuditLogParams struct {
	EntityType  string      `json:"entity_type"`
	EntityID    int32       `json:"entity_id"`
	Action      string      `json:"action"`
	ActorUserID pgtype.Int4 `json:"actor_user_id"`
	BeforeValue []byte      `json:"before_value"`
	AfterValue  []byte      `json:"after_value"`
}

func (q *Queries) CreateWorkflowConfigurationAuditLog(ctx context.Context, arg CreateWorkflowConfigurationAuditLogParams) (WorkflowConfigurationAuditLog, error) {
	row := q.db.QueryRow(ctx, createWorkflowConfigurationAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorUserID,
		arg.BeforeValue,
		arg.AfterValue,
	)
	var i WorkflowConfigurationAuditLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.ActorUserID,
		&i.BeforeValue,
		&i.AfterValue,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowInputSchema = `-- name: CreateWorkflowInputSchema :one
INSERT INTO "workflow_input_schema" (workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type CreateWorkflowInputSchemaParams struct {
	WorkflowID      int32       `json:"workflow_id"`
	Code            string      `json:"code"`
	VersionNumber   int32       `json:"version_number"`
	SchemaJson      []byte      `json:"schema_json"`
	Status          string      `json:"status"`
	IsDefault       bool        `json:"is_default"`
	CreatedByUserID pgtype.Int4 `json:"created_by_user_id"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) CreateWorkflowInputSchema(ctx context.Context, arg CreateWorkflowInputSchemaParams) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, createWorkflowInputSchema,
		arg.WorkflowID,
		arg.Code,
		arg.VersionNumber,
		arg.SchemaJson,
		arg.Status,
		arg.IsDefault,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDefaultWorkflowInputSchema = `-- name: GetDefaultWorkflowInputSchema :one
SELECT id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_input_schema"
WHERE workflow_id = $1 AND is_default = TRUE AND deleted_at IS NULL
`

func (q *Queries) GetDefaultWorkflowInputSchema(ctx context.Context, workflowID int32) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, getDefaultWorkflowInputSchema, workflowID)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNextWorkflowInputSchemaVersionNumber = `-- name: GetNextWorkflowInputSchemaVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int + 1 FROM "workflow_input_schema"
WHERE workflow_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNextWorkflowInputSchemaVersionNumber(ctx context.Context, workflowID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextWorkflowInputSchemaVersionNumber, workflowID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getWorkflowInputSchemaByCode = `-- name: GetWorkflowInputSchemaByCode :one
SELECT id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_input_schema"
WHERE workflow_id = $1 AND code = $2 AND deleted_at IS NULL
`

type GetWorkflowInputSchemaByCodeParams struct {
	WorkflowID int32  `json:"workflow_id"`
	Code       string `json:"code"`
}

func (q *Queries) GetWorkflowInputSchemaByCode(ctx context.Context, arg GetWorkflowInputSchemaByCodeParams) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, getWorkflowInputSchemaByCode, arg.WorkflowID, arg.Code)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkflowInputSchemaByID = `-- name: GetWorkflowInputSchemaByID :one
SELECT id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_input_schema"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowInputSchemaByID(ctx context.Context, id int32) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, getWorkflowInputSchemaByID, id)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hasInputSchemaUsage = `-- name: HasInputSchemaUsage :one
SELECT EXISTS (
    SELECT 1 FROM "message" m
    WHERE m.workflow_input_schema_id = $1 AND m.deleted_at IS NULL
    UNION ALL
    SELECT 1 FROM "workflow_version_input_schema_compatibility" c
    WHERE c.workflow_input_schema_id = $1 AND c.deleted_at IS NULL
    UNION ALL
    SELECT 1 FROM "workflow_experiment_scope" s
    WHERE s.workflow_input_schema_id = $1 AND s.deleted_at IS NULL
) AS has_usage
`

func (q *Queries) HasInputSchemaUsage(ctx context.Context, workflowInputSchemaID pgtype.Int4) (bool, error) {
	row := q.db.QueryRow(ctx, hasInputSchemaUsage, workflowInputSchemaID)
	var has_usage bool
	err := row.Scan(&has_usage)
	return has_usage, err
}

const listWorkflowInputSchemasByWorkflowID = `-- name: ListWorkflowInputSchemasByWorkflowID :many
SELECT id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at FROM "workflow_input_schema"
WHERE workflow_id = $1 AND deleted_at IS NULL
ORDER BY is_default DESC, version_number DESC, id DESC
`

func (q *Queries) ListWorkflowInputSchemasByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowInputSchema, error) {
	rows, err := q.db.Query(ctx, listWorkflowInputSchemasByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowInputSchema
	for rows.Next() {
		var i WorkflowInputSchema
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Code,
			&i.VersionNumber,
			&i.SchemaJson,
			&i.Status,
			&i.IsDefault,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultWorkflowInputSchema = `-- name: SetDefaultWorkflowInputSchema :one
UPDATE "workflow_input_schema"
SET is_default = TRUE,
    updated_by_user_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'active' AND deleted_at IS NULL
RETURNING id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type SetDefaultWorkflowInputSchemaParams struct {
	ID              int32       `json:"id"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) SetDefaultWorkflowInputSchema(ctx context.Context, arg SetDefaultWorkflowInputSchemaParams) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, setDefaultWorkflowInputSchema, arg.ID, arg.UpdatedByUserID)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteWorkflowInputSchema = `-- name: SoftDeleteWorkflowInputSchema :exec
UPDATE "workflow_input_schema"
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowInputSchema(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflowInputSchema, id)
	return err
}

const updateWorkflowInputSchemaRecord = `-- name: UpdateWorkflowInputSchemaRecord :one
UPDATE "workflow_input_schema"
SET code = $2,
    version_number = $3,
    schema_json = $4,
    updated_by_user_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type UpdateWorkflowInputSchemaRecordParams struct {
	ID              int32       `json:"id"`
	Code            string      `json:"code"`
	VersionNumber   int32       `json:"version_number"`
	SchemaJson      []byte      `json:"schema_json"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) UpdateWorkflowInputSchemaRecord(ctx context.Context, arg UpdateWorkflowInputSchemaRecordParams) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, updateWorkflowInputSchemaRecord,
		arg.ID,
		arg.Code,
		arg.VersionNumber,
		arg.SchemaJson,
		arg.UpdatedByUserID,
	)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkflowInputSchemaStatus = `-- name: UpdateWorkflowInputSchemaStatus :one
UPDATE "workflow_input_schema"
SET status = $2,
    updated_by_user_id = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_id, code, version_number, schema_json, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at, deleted_at
`

type UpdateWorkflowInputSchemaStatusParams struct {
	ID              int32       `json:"id"`
	Status          string      `json:"status"`
	UpdatedByUserID pgtype.Int4 `json:"updated_by_user_id"`
}

func (q *Queries) UpdateWorkflowInputSchemaStatus(ctx context.Context, arg UpdateWorkflowInputSchemaStatusParams) (WorkflowInputSchema, error) {
	row := q.db.QueryRow(ctx, updateWorkflowInputSchemaStatus, arg.ID, arg.Status, arg.UpdatedByUserID)
	var i WorkflowInputSchema
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Code,
		&i.VersionNumber,
		&i.SchemaJson,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
