// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker_settings_schema.sql

package db

import (
	"context"
	"encoding/json"
)

const createWorkerSettingsSchema = `-- name: CreateWorkerSettingsSchema :one
INSERT INTO "worker_settings_schema" (work_type_id, "version", settings_schema, input_schema, output_schema)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, work_type_id, version, settings_schema, input_schema, output_schema, created_at, updated_at, deleted_at
`

type CreateWorkerSettingsSchemaParams struct {
	WorkTypeID     int32           `json:"work_type_id"`
	Version        string          `json:"version"`
	SettingsSchema json.RawMessage `json:"settings_schema"`
	InputSchema    json.RawMessage `json:"input_schema"`
	OutputSchema   json.RawMessage `json:"output_schema"`
}

func (q *Queries) CreateWorkerSettingsSchema(ctx context.Context, arg CreateWorkerSettingsSchemaParams) (WorkerSettingsSchema, error) {
	row := q.db.QueryRowContext(ctx, createWorkerSettingsSchema,
		arg.WorkTypeID,
		arg.Version,
		arg.SettingsSchema,
		arg.InputSchema,
		arg.OutputSchema,
	)
	var i WorkerSettingsSchema
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.Version,
		&i.SettingsSchema,
		&i.InputSchema,
		&i.OutputSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkerSettingsSchemaByID = `-- name: GetWorkerSettingsSchemaByID :one
SELECT id, work_type_id, version, settings_schema, input_schema, output_schema, created_at, updated_at, deleted_at FROM "worker_settings_schema"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkerSettingsSchemaByID(ctx context.Context, id int32) (WorkerSettingsSchema, error) {
	row := q.db.QueryRowContext(ctx, getWorkerSettingsSchemaByID, id)
	var i WorkerSettingsSchema
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.Version,
		&i.SettingsSchema,
		&i.InputSchema,
		&i.OutputSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkerSettingsSchemasByWorkTypeID = `-- name: ListWorkerSettingsSchemasByWorkTypeID :many
SELECT id, work_type_id, version, settings_schema, input_schema, output_schema, created_at, updated_at, deleted_at FROM "worker_settings_schema"
WHERE work_type_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListWorkerSettingsSchemasByWorkTypeID(ctx context.Context, workTypeID int32) ([]WorkerSettingsSchema, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerSettingsSchemasByWorkTypeID, workTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerSettingsSchema
	for rows.Next() {
		var i WorkerSettingsSchema
		if err := rows.Scan(
			&i.ID,
			&i.WorkTypeID,
			&i.Version,
			&i.SettingsSchema,
			&i.InputSchema,
			&i.OutputSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkerSettingsSchema = `-- name: SoftDeleteWorkerSettingsSchema :exec
UPDATE "worker_settings_schema"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkerSettingsSchema(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteWorkerSettingsSchema, id)
	return err
}
