// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: work_type_token.sql

package db

import (
	"context"
)

const createWorkTypeToken = `-- name: CreateWorkTypeToken :one
INSERT INTO "work_type_token" (work_type_id, token_hash, is_active)
VALUES ($1, $2, $3)
RETURNING id, work_type_id, token_hash, is_active, created_at, deleted_at
`

type CreateWorkTypeTokenParams struct {
	WorkTypeID int32  `json:"work_type_id"`
	TokenHash  string `json:"token_hash"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) CreateWorkTypeToken(ctx context.Context, arg CreateWorkTypeTokenParams) (WorkTypeToken, error) {
	row := q.db.QueryRowContext(ctx, createWorkTypeToken, arg.WorkTypeID, arg.TokenHash, arg.IsActive)
	var i WorkTypeToken
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateWorkTypeToken = `-- name: DeactivateWorkTypeToken :exec
UPDATE "work_type_token"
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateWorkTypeToken(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deactivateWorkTypeToken, id)
	return err
}

const getActiveWorkTypeTokenByHash = `-- name: GetActiveWorkTypeTokenByHash :one
SELECT id, work_type_id, token_hash, is_active, created_at, deleted_at FROM "work_type_token"
WHERE token_hash = $1 AND is_active = TRUE AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveWorkTypeTokenByHash(ctx context.Context, tokenHash string) (WorkTypeToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveWorkTypeTokenByHash, tokenHash)
	var i WorkTypeToken
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkTypeTokenByWorkTypeID = `-- name: GetWorkTypeTokenByWorkTypeID :one
SELECT id, work_type_id, token_hash, is_active, created_at, deleted_at FROM "work_type_token"
WHERE work_type_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWorkTypeTokenByWorkTypeID(ctx context.Context, workTypeID int32) (WorkTypeToken, error) {
	row := q.db.QueryRowContext(ctx, getWorkTypeTokenByWorkTypeID, workTypeID)
	var i WorkTypeToken
	err := row.Scan(
		&i.ID,
		&i.WorkTypeID,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteWorkTypeToken = `-- name: SoftDeleteWorkTypeToken :exec
UPDATE "work_type_token"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkTypeToken(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteWorkTypeToken, id)
	return err
}
