// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker_settings_revision.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createWorkerSettingsRevision = `-- name: CreateWorkerSettingsRevision :one
INSERT INTO "worker_settings_revision" (worker_settings_schema_id, created_by_user_id, settings_data)
VALUES ($1, $2, $3)
RETURNING id, worker_settings_schema_id, created_by_user_id, settings_data, created_at
`

type CreateWorkerSettingsRevisionParams struct {
	WorkerSettingsSchemaID int32           `json:"worker_settings_schema_id"`
	CreatedByUserID        sql.NullInt32   `json:"created_by_user_id"`
	SettingsData           json.RawMessage `json:"settings_data"`
}

func (q *Queries) CreateWorkerSettingsRevision(ctx context.Context, arg CreateWorkerSettingsRevisionParams) (WorkerSettingsRevision, error) {
	row := q.db.QueryRowContext(ctx, createWorkerSettingsRevision, arg.WorkerSettingsSchemaID, arg.CreatedByUserID, arg.SettingsData)
	var i WorkerSettingsRevision
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsSchemaID,
		&i.CreatedByUserID,
		&i.SettingsData,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkerSettingsRevisionByID = `-- name: GetWorkerSettingsRevisionByID :one
SELECT id, worker_settings_schema_id, created_by_user_id, settings_data, created_at FROM "worker_settings_revision"
WHERE id = $1
`

func (q *Queries) GetWorkerSettingsRevisionByID(ctx context.Context, id int32) (WorkerSettingsRevision, error) {
	row := q.db.QueryRowContext(ctx, getWorkerSettingsRevisionByID, id)
	var i WorkerSettingsRevision
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsSchemaID,
		&i.CreatedByUserID,
		&i.SettingsData,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkerSettingsRevisionsBySchemaID = `-- name: ListWorkerSettingsRevisionsBySchemaID :many
SELECT id, worker_settings_schema_id, created_by_user_id, settings_data, created_at FROM "worker_settings_revision"
WHERE worker_settings_schema_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkerSettingsRevisionsBySchemaID(ctx context.Context, workerSettingsSchemaID int32) ([]WorkerSettingsRevision, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerSettingsRevisionsBySchemaID, workerSettingsSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerSettingsRevision
	for rows.Next() {
		var i WorkerSettingsRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkerSettingsSchemaID,
			&i.CreatedByUserID,
			&i.SettingsData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
