// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: work_type.sql

package db

import (
	"context"
	"database/sql"
)

const createWorkType = `-- name: CreateWorkType :one
INSERT INTO "work_type" ("name", code, description)
VALUES ($1, $2, $3)
RETURNING id, name, code, description, created_at, updated_at, deleted_at
`

type CreateWorkTypeParams struct {
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateWorkType(ctx context.Context, arg CreateWorkTypeParams) (WorkType, error) {
	row := q.db.QueryRowContext(ctx, createWorkType, arg.Name, arg.Code, arg.Description)
	var i WorkType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkTypeByCode = `-- name: GetWorkTypeByCode :one
SELECT id, name, code, description, created_at, updated_at, deleted_at FROM "work_type"
WHERE code = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWorkTypeByCode(ctx context.Context, code string) (WorkType, error) {
	row := q.db.QueryRowContext(ctx, getWorkTypeByCode, code)
	var i WorkType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkTypeByID = `-- name: GetWorkTypeByID :one
SELECT id, name, code, description, created_at, updated_at, deleted_at FROM "work_type"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkTypeByID(ctx context.Context, id int32) (WorkType, error) {
	row := q.db.QueryRowContext(ctx, getWorkTypeByID, id)
	var i WorkType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkTypes = `-- name: ListWorkTypes :many
SELECT id, name, code, description, created_at, updated_at, deleted_at FROM "work_type"
WHERE deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListWorkTypes(ctx context.Context) ([]WorkType, error) {
	rows, err := q.db.QueryContext(ctx, listWorkTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkType
	for rows.Next() {
		var i WorkType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkType = `-- name: SoftDeleteWorkType :exec
UPDATE "work_type"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteWorkType, id)
	return err
}
