// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_run_step_attempt.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createWorkflowRunStepAttempt = `-- name: CreateWorkflowRunStepAttempt :one
INSERT INTO "workflow_run_step_attempt" (workflow_run_step_id, worker_id, attempt_number, status)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_run_step_id, worker_id, attempt_number, status, error_code, error_message, output_data, started_at, completed_at
`

type CreateWorkflowRunStepAttemptParams struct {
	WorkflowRunStepID int32         `json:"workflow_run_step_id"`
	WorkerID          sql.NullInt32 `json:"worker_id"`
	AttemptNumber     int32         `json:"attempt_number"`
	Status            string        `json:"status"`
}

func (q *Queries) CreateWorkflowRunStepAttempt(ctx context.Context, arg CreateWorkflowRunStepAttemptParams) (WorkflowRunStepAttempt, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowRunStepAttempt,
		arg.WorkflowRunStepID,
		arg.WorkerID,
		arg.AttemptNumber,
		arg.Status,
	)
	var i WorkflowRunStepAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunStepID,
		&i.WorkerID,
		&i.AttemptNumber,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowRunStepAttemptByID = `-- name: GetWorkflowRunStepAttemptByID :one
SELECT id, workflow_run_step_id, worker_id, attempt_number, status, error_code, error_message, output_data, started_at, completed_at FROM "workflow_run_step_attempt"
WHERE id = $1
`

func (q *Queries) GetWorkflowRunStepAttemptByID(ctx context.Context, id int32) (WorkflowRunStepAttempt, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRunStepAttemptByID, id)
	var i WorkflowRunStepAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunStepID,
		&i.WorkerID,
		&i.AttemptNumber,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAttemptsByRunStepID = `-- name: ListAttemptsByRunStepID :many
SELECT id, workflow_run_step_id, worker_id, attempt_number, status, error_code, error_message, output_data, started_at, completed_at FROM "workflow_run_step_attempt"
WHERE workflow_run_step_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListAttemptsByRunStepID(ctx context.Context, workflowRunStepID int32) ([]WorkflowRunStepAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptsByRunStepID, workflowRunStepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRunStepAttempt
	for rows.Next() {
		var i WorkflowRunStepAttempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunStepID,
			&i.WorkerID,
			&i.AttemptNumber,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.OutputData,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStepAttemptStatus = `-- name: UpdateWorkflowRunStepAttemptStatus :one
UPDATE "workflow_run_step_attempt"
SET status = $2, error_code = $3, error_message = $4, output_data = $5, completed_at = $6
WHERE id = $1
RETURNING id, workflow_run_step_id, worker_id, attempt_number, status, error_code, error_message, output_data, started_at, completed_at
`

type UpdateWorkflowRunStepAttemptStatusParams struct {
	ID           int32                 `json:"id"`
	Status       string                `json:"status"`
	ErrorCode    sql.NullString        `json:"error_code"`
	ErrorMessage sql.NullString        `json:"error_message"`
	OutputData   pqtype.NullRawMessage `json:"output_data"`
	CompletedAt  sql.NullTime          `json:"completed_at"`
}

func (q *Queries) UpdateWorkflowRunStepAttemptStatus(ctx context.Context, arg UpdateWorkflowRunStepAttemptStatusParams) (WorkflowRunStepAttempt, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowRunStepAttemptStatus,
		arg.ID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OutputData,
		arg.CompletedAt,
	)
	var i WorkflowRunStepAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunStepID,
		&i.WorkerID,
		&i.AttemptNumber,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.OutputData,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
