// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_step.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createWorkflowStep = `-- name: CreateWorkflowStep :one
INSERT INTO "workflow_step" (workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, created_at, updated_at, deleted_at
`

type CreateWorkflowStepParams struct {
	WorkflowVersionID        int32                 `json:"workflow_version_id"`
	StepType                 string                `json:"step_type"`
	WorkTypeID               sql.NullInt32         `json:"work_type_id"`
	WorkerSettingsRevisionID sql.NullInt32         `json:"worker_settings_revision_id"`
	ControlKind              sql.NullString        `json:"control_kind"`
	ControlSettings          pqtype.NullRawMessage `json:"control_settings"`
	InputMapping             pqtype.NullRawMessage `json:"input_mapping"`
}

func (q *Queries) CreateWorkflowStep(ctx context.Context, arg CreateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowStep,
		arg.WorkflowVersionID,
		arg.StepType,
		arg.WorkTypeID,
		arg.WorkerSettingsRevisionID,
		arg.ControlKind,
		arg.ControlSettings,
		arg.InputMapping,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.StepType,
		&i.WorkTypeID,
		&i.WorkerSettingsRevisionID,
		&i.ControlKind,
		&i.ControlSettings,
		&i.InputMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteWorkflowStepsByVersionID = `-- name: DeleteWorkflowStepsByVersionID :exec
UPDATE "workflow_step"
SET deleted_at = CURRENT_TIMESTAMP
WHERE workflow_version_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteWorkflowStepsByVersionID(ctx context.Context, workflowVersionID int32) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowStepsByVersionID, workflowVersionID)
	return err
}

const getWorkflowStepByID = `-- name: GetWorkflowStepByID :one
SELECT id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, created_at, updated_at, deleted_at FROM "workflow_step"
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkflowStepByID(ctx context.Context, id int32) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowStepByID, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.StepType,
		&i.WorkTypeID,
		&i.WorkerSettingsRevisionID,
		&i.ControlKind,
		&i.ControlSettings,
		&i.InputMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkflowStepsByVersionID = `-- name: ListWorkflowStepsByVersionID :many
SELECT id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, created_at, updated_at, deleted_at FROM "workflow_step"
WHERE workflow_version_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListWorkflowStepsByVersionID(ctx context.Context, workflowVersionID int32) ([]WorkflowStep, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowStepsByVersionID, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStep
	for rows.Next() {
		var i WorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.StepType,
			&i.WorkTypeID,
			&i.WorkerSettingsRevisionID,
			&i.ControlKind,
			&i.ControlSettings,
			&i.InputMapping,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflowStep = `-- name: SoftDeleteWorkflowStep :exec
UPDATE "workflow_step"
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkflowStep(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteWorkflowStep, id)
	return err
}

const updateWorkflowStep = `-- name: UpdateWorkflowStep :one
UPDATE "workflow_step"
SET step_type = $2,
    work_type_id = $3,
    worker_settings_revision_id = $4,
    control_kind = $5,
    control_settings = $6,
    input_mapping = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workflow_version_id, step_type, work_type_id, worker_settings_revision_id, control_kind, control_settings, input_mapping, created_at, updated_at, deleted_at
`

type UpdateWorkflowStepParams struct {
	ID                       int32                 `json:"id"`
	StepType                 string                `json:"step_type"`
	WorkTypeID               sql.NullInt32         `json:"work_type_id"`
	WorkerSettingsRevisionID sql.NullInt32         `json:"worker_settings_revision_id"`
	ControlKind              sql.NullString        `json:"control_kind"`
	ControlSettings          pqtype.NullRawMessage `json:"control_settings"`
	InputMapping             pqtype.NullRawMessage `json:"input_mapping"`
}

func (q *Queries) UpdateWorkflowStep(ctx context.Context, arg UpdateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowStep,
		arg.ID,
		arg.StepType,
		arg.WorkTypeID,
		arg.WorkerSettingsRevisionID,
		arg.ControlKind,
		arg.ControlSettings,
		arg.InputMapping,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.StepType,
		&i.WorkTypeID,
		&i.WorkerSettingsRevisionID,
		&i.ControlKind,
		&i.ControlSettings,
		&i.InputMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
