env: "local"
manager_url: "http://localhost:3009"
bootstrap_token: "dev-telegram-org-1-bootstrap-token"
nats_ca_file: "configs/nats/certs/ca.pem"
token: "decedb9c-3a96-4b0f-9638-f2276ec624dd"
server_url: "http://localhost:8080"
