workers:
  - name: smtp-basic
    app: smtp
    variant: basic
    count: 5

  - name: smtp-auth
    app: smtp
    variant: auth
    count: 1

  - name: html-template
    app: html
    variant: basic
    count: 1
