// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID                int32            `json:"id"`
	MessageID         pgtype.Int4      `json:"message_id"`
	WorkflowRunStepID pgtype.Int4      `json:"workflow_run_step_id"`
	Name              string           `json:"name"`
	Bucket            string           `json:"bucket"`
	ObjectKey         string           `json:"object_key"`
	ContentType       string           `json:"content_type"`
	SizeBytes         int32            `json:"size_bytes"`
	Hash              string           `json:"hash"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}

type Message struct {
	ID                    int32            `json:"id"`
	WorkflowID            int32            `json:"workflow_id"`
	ExternalMessageID     pgtype.Text      `json:"external_message_id"`
	OverriddenPriority    pgtype.Int4      `json:"overridden_priority"`
	Value                 []byte           `json:"value"`
	Status                string           `json:"status"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
	WorkflowInputSchemaID pgtype.Int4      `json:"workflow_input_schema_id"`
	IdempotencyKey        pgtype.Text      `json:"idempotency_key"`
	Metadata              []byte           `json:"metadata"`
	ErrorMessage          pgtype.Text      `json:"error_message"`
}

type Organization struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Code      string           `json:"code"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Permission struct {
	ID        int32  `json:"id"`
	Slug      string `json:"slug"`
	IsPrivate bool   `json:"is_private"`
}

type PermissionRole struct {
	PermissionID int32 `json:"permission_id"`
	RoleID       int32 `json:"role_id"`
}

type RevisionRateLimit struct {
	ID                       int32            `json:"id"`
	WorkerSettingsRevisionID int32            `json:"worker_settings_revision_id"`
	Limit                    int32            `json:"limit"`
	WindowSeconds            int32            `json:"window_seconds"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID             int32            `json:"id"`
	OrganizationID pgtype.Int4      `json:"organization_id"`
	Name           string           `json:"name"`
	Description    pgtype.Text      `json:"description"`
	IsSystem       bool             `json:"is_system"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type RoleUser struct {
	RoleID int32 `json:"role_id"`
	UserID int32 `json:"user_id"`
}

type System struct {
	ID             int32            `json:"id"`
	OrganizationID pgtype.Int4      `json:"organization_id"`
	UserCreatorID  pgtype.Int4      `json:"user_creator_id"`
	Name           string           `json:"name"`
	Description    pgtype.Text      `json:"description"`
	IsActive       bool             `json:"is_active"`
	Priority       int32            `json:"priority"`
	PublicToken    pgtype.Text      `json:"public_token"`
	PrivateToken   pgtype.Text      `json:"private_token"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type SystemToken struct {
	ID           int32            `json:"id"`
	SystemID     int32            `json:"system_id"`
	Name         string           `json:"name"`
	PublicToken  string           `json:"public_token"`
	PrivateToken string           `json:"private_token"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID                      int32            `json:"id"`
	OrganizationID          pgtype.Int4      `json:"organization_id"`
	LastName                string           `json:"last_name"`
	FirstName               string           `json:"first_name"`
	Patronymic              pgtype.Text      `json:"patronymic"`
	Email                   string           `json:"email"`
	Password                string           `json:"password"`
	ResetPasswordAfterLogin pgtype.Bool      `json:"reset_password_after_login"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
	DeletedAt               pgtype.Timestamp `json:"deleted_at"`
}

type WorkType struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Description pgtype.Text      `json:"description"`
	Meta        []byte           `json:"meta"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type Worker struct {
	ID                     int32            `json:"id"`
	OrganizationID         int32            `json:"organization_id"`
	WorkTypeID             int32            `json:"work_type_id"`
	WorkerSettingsSchemaID int32            `json:"worker_settings_schema_id"`
	Name                   string           `json:"name"`
	Metadata               []byte           `json:"metadata"`
	RegisteredAt           pgtype.Timestamp `json:"registered_at"`
	LastHeartbeatAt        pgtype.Timestamp `json:"last_heartbeat_at"`
}

type WorkerBootstrapToken struct {
	ID                     int32            `json:"id"`
	OrganizationID         int32            `json:"organization_id"`
	WorkTypeID             int32            `json:"work_type_id"`
	Name                   string           `json:"name"`
	Description            pgtype.Text      `json:"description"`
	TokenHash              string           `json:"token_hash"`
	Status                 string           `json:"status"`
	MaxActiveWorkers       int32            `json:"max_active_workers"`
	TotalRegistrationCount int32            `json:"total_registration_count"`
	ExpiresAt              pgtype.Timestamp `json:"expires_at"`
	LastUsedAt             pgtype.Timestamp `json:"last_used_at"`
	CreatedByUserID        pgtype.Int4      `json:"created_by_user_id"`
	RevokedAt              pgtype.Timestamp `json:"revoked_at"`
	RevokedByUserID        pgtype.Int4      `json:"revoked_by_user_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
}

type WorkerNatsSession struct {
	ID                   int32            `json:"id"`
	WorkerID             int32            `json:"worker_id"`
	BootstrapTokenID     int32            `json:"bootstrap_token_id"`
	NatsAccountPublicKey string           `json:"nats_account_public_key"`
	NatsUserPublicKey    string           `json:"nats_user_public_key"`
	NatsUserJwt          string           `json:"nats_user_jwt"`
	Permissions          []byte           `json:"permissions"`
	RevokedAt            pgtype.Timestamp `json:"revoked_at"`
	RevokedByUserID      pgtype.Int4      `json:"revoked_by_user_id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	NatsUserSeed         string           `json:"nats_user_seed"`
	NatsUserCredentials  string           `json:"nats_user_credentials"`
}

type WorkerSettingsRevision struct {
	ID                     int32            `json:"id"`
	WorkerSettingsSchemaID int32            `json:"worker_settings_schema_id"`
	CreatedByUserID        pgtype.Int4      `json:"created_by_user_id"`
	SettingsData           []byte           `json:"settings_data"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
}

type WorkerSettingsSchema struct {
	ID             int32            `json:"id"`
	WorkTypeID     int32            `json:"work_type_id"`
	Version        string           `json:"version"`
	SettingsSchema []byte           `json:"settings_schema"`
	InputSchema    []byte           `json:"input_schema"`
	OutputSchema   []byte           `json:"output_schema"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type Workflow struct {
	ID          int32            `json:"id"`
	SystemID    int32            `json:"system_id"`
	Name        string           `json:"name"`
	Priority    int32            `json:"priority"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowConfigurationAuditLog struct {
	ID          int32            `json:"id"`
	EntityType  string           `json:"entity_type"`
	EntityID    int32            `json:"entity_id"`
	Action      string           `json:"action"`
	ActorUserID pgtype.Int4      `json:"actor_user_id"`
	BeforeValue []byte           `json:"before_value"`
	AfterValue  []byte           `json:"after_value"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type WorkflowExperiment struct {
	ID              int32            `json:"id"`
	WorkflowID      int32            `json:"workflow_id"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	ExperimentType  string           `json:"experiment_type"`
	Status          string           `json:"status"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	EndedAt         pgtype.Timestamp `json:"ended_at"`
	CreatedByUserID pgtype.Int4      `json:"created_by_user_id"`
	UpdatedByUserID pgtype.Int4      `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowExperimentScope struct {
	ID                        int32            `json:"id"`
	WorkflowExperimentID      int32            `json:"workflow_experiment_id"`
	WorkflowInputSchemaID     int32            `json:"workflow_input_schema_id"`
	TrafficConditions         []byte           `json:"traffic_conditions"`
	ConditionsHash            string           `json:"conditions_hash"`
	TrafficPercent            int32            `json:"traffic_percent"`
	FallbackPolicy            string           `json:"fallback_policy"`
	FallbackWorkflowVersionID pgtype.Int4      `json:"fallback_workflow_version_id"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	DeletedAt                 pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowExperimentVariant struct {
	ID                        int32            `json:"id"`
	WorkflowExperimentScopeID int32            `json:"workflow_experiment_scope_id"`
	WorkflowVersionID         int32            `json:"workflow_version_id"`
	TrafficWeight             int32            `json:"traffic_weight"`
	IsControlGroup            bool             `json:"is_control_group"`
	IsActive                  bool             `json:"is_active"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	DeletedAt                 pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowInputMapper struct {
	ID              int32            `json:"id"`
	WorkflowID      int32            `json:"workflow_id"`
	MapperType      string           `json:"mapper_type"`
	Rules           []byte           `json:"rules"`
	IsActive        bool             `json:"is_active"`
	CreatedByUserID pgtype.Int4      `json:"created_by_user_id"`
	UpdatedByUserID pgtype.Int4      `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowInputSchema struct {
	ID              int32            `json:"id"`
	WorkflowID      int32            `json:"workflow_id"`
	Code            string           `json:"code"`
	VersionNumber   int32            `json:"version_number"`
	SchemaJson      []byte           `json:"schema_json"`
	Status          string           `json:"status"`
	IsDefault       bool             `json:"is_default"`
	CreatedByUserID pgtype.Int4      `json:"created_by_user_id"`
	UpdatedByUserID pgtype.Int4      `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowRun struct {
	ID                          int32            `json:"id"`
	WorkflowVersionID           int32            `json:"workflow_version_id"`
	MessageID                   int32            `json:"message_id"`
	TemporalWorkflowID          pgtype.Text      `json:"temporal_workflow_id"`
	Status                      string           `json:"status"`
	StartedAt                   pgtype.Timestamp `json:"started_at"`
	CompletedAt                 pgtype.Timestamp `json:"completed_at"`
	ErrorMessage                pgtype.Text      `json:"error_message"`
	WorkflowExperimentID        pgtype.Int4      `json:"workflow_experiment_id"`
	WorkflowExperimentScopeID   pgtype.Int4      `json:"workflow_experiment_scope_id"`
	WorkflowExperimentVariantID pgtype.Int4      `json:"workflow_experiment_variant_id"`
	InputSchemaCompatibilityID  pgtype.Int4      `json:"input_schema_compatibility_id"`
	SelectionReason             string           `json:"selection_reason"`
	VersionInputData            []byte           `json:"version_input_data"`
	RoutingDecision             []byte           `json:"routing_decision"`
}

type WorkflowRunStep struct {
	ID             int32            `json:"id"`
	WorkflowRunID  int32            `json:"workflow_run_id"`
	WorkflowStepID int32            `json:"workflow_step_id"`
	WorkerID       pgtype.Int4      `json:"worker_id"`
	TemporalStepID pgtype.Text      `json:"temporal_step_id"`
	Status         string           `json:"status"`
	Outcome        pgtype.Text      `json:"outcome"`
	InputData      []byte           `json:"input_data"`
	OutputData     []byte           `json:"output_data"`
	StartedAt      pgtype.Timestamp `json:"started_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
	ErrorMessage   pgtype.Text      `json:"error_message"`
}

type WorkflowRunStepAttempt struct {
	ID                int32            `json:"id"`
	WorkflowRunStepID int32            `json:"workflow_run_step_id"`
	WorkerID          pgtype.Int4      `json:"worker_id"`
	AttemptNumber     int32            `json:"attempt_number"`
	Status            string           `json:"status"`
	ErrorCode         pgtype.Text      `json:"error_code"`
	ErrorMessage      pgtype.Text      `json:"error_message"`
	OutputData        []byte           `json:"output_data"`
	StartedAt         pgtype.Timestamp `json:"started_at"`
	CompletedAt       pgtype.Timestamp `json:"completed_at"`
}

type WorkflowStep struct {
	ID                       int32            `json:"id"`
	WorkflowVersionID        int32            `json:"workflow_version_id"`
	Name                     string           `json:"name"`
	StepType                 string           `json:"step_type"`
	WorkTypeID               pgtype.Int4      `json:"work_type_id"`
	WorkerSettingsRevisionID pgtype.Int4      `json:"worker_settings_revision_id"`
	ControlKind              pgtype.Text      `json:"control_kind"`
	ControlSettings          []byte           `json:"control_settings"`
	InputMapping             []byte           `json:"input_mapping"`
	CanvasPosition           []byte           `json:"canvas_position"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
	DeletedAt                pgtype.Timestamp `json:"deleted_at"`
}

type WorkflowStepDependency struct {
	StepID          int32       `json:"step_id"`
	DependsOnStepID int32       `json:"depends_on_step_id"`
	Outcome         pgtype.Text `json:"outcome"`
	OutputIndex     int32       `json:"output_index"`
}

type WorkflowToken struct {
	SystemTokenID int32            `json:"system_token_id"`
	WorkflowID    int32            `json:"workflow_id"`
	GrantedAt     pgtype.Timestamp `json:"granted_at"`
}

type WorkflowVersion struct {
	ID              int32            `json:"id"`
	WorkflowID      int32            `json:"workflow_id"`
	CreatedByUserID pgtype.Int4      `json:"created_by_user_id"`
	VersionNumber   int32            `json:"version_number"`
	Name            pgtype.Text      `json:"name"`
	IsValid         bool             `json:"is_valid"`
	IsActive        bool             `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
	LockedAt        pgtype.Timestamp `json:"locked_at"`
	PublishedAt     pgtype.Timestamp `json:"published_at"`
	ArchivedAt      pgtype.Timestamp `json:"archived_at"`
	UpdatedByUserID pgtype.Int4      `json:"updated_by_user_id"`
}

type WorkflowVersionInputSchemaCompatibility struct {
	ID                    int32            `json:"id"`
	WorkflowVersionID     int32            `json:"workflow_version_id"`
	WorkflowInputSchemaID int32            `json:"workflow_input_schema_id"`
	CompatibilityType     string           `json:"compatibility_type"`
	WorkflowInputMapperID pgtype.Int4      `json:"workflow_input_mapper_id"`
	DefaultValues         []byte           `json:"default_values"`
	IsActive              bool             `json:"is_active"`
	IsDefaultRoute        bool             `json:"is_default_route"`
	CreatedByUserID       pgtype.Int4      `json:"created_by_user_id"`
	UpdatedByUserID       pgtype.Int4      `json:"updated_by_user_id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
}
