// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permission.sql

package db

import (
	"context"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO "permission" (slug, is_private)
VALUES ($1, $2)
RETURNING id, slug, is_private
`

type CreatePermissionParams struct {
	Slug      string `json:"slug"`
	IsPrivate bool   `json:"is_private"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Slug, arg.IsPrivate)
	var i Permission
	err := row.Scan(&i.ID, &i.Slug, &i.IsPrivate)
	return i, err
}

const getPermissionBySlug = `-- name: GetPermissionBySlug :one
SELECT id, slug, is_private FROM "permission" WHERE slug = $1
`

func (q *Queries) GetPermissionBySlug(ctx context.Context, slug string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionBySlug, slug)
	var i Permission
	err := row.Scan(&i.ID, &i.Slug, &i.IsPrivate)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, slug, is_private FROM "permission" ORDER BY slug
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Slug, &i.IsPrivate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
