// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: revision_rate_limit.sql

package db

import (
	"context"
)

const createRevisionRateLimit = `-- name: CreateRevisionRateLimit :one
INSERT INTO "revision_rate_limit" (worker_settings_revision_id, "limit", window_seconds)
VALUES ($1, $2, $3)
RETURNING id, worker_settings_revision_id, "limit", window_seconds, created_at, updated_at
`

type CreateRevisionRateLimitParams struct {
	WorkerSettingsRevisionID int32 `json:"worker_settings_revision_id"`
	Limit                    int32 `json:"limit"`
	WindowSeconds            int32 `json:"window_seconds"`
}

func (q *Queries) CreateRevisionRateLimit(ctx context.Context, arg CreateRevisionRateLimitParams) (RevisionRateLimit, error) {
	row := q.db.QueryRow(ctx, createRevisionRateLimit, arg.WorkerSettingsRevisionID, arg.Limit, arg.WindowSeconds)
	var i RevisionRateLimit
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsRevisionID,
		&i.Limit,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRevisionRateLimit = `-- name: DeleteRevisionRateLimit :exec
DELETE FROM "revision_rate_limit"
WHERE id = $1
`

func (q *Queries) DeleteRevisionRateLimit(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRevisionRateLimit, id)
	return err
}

const listRevisionRateLimitsByRevisionID = `-- name: ListRevisionRateLimitsByRevisionID :many
SELECT id, worker_settings_revision_id, "limit", window_seconds, created_at, updated_at FROM "revision_rate_limit"
WHERE worker_settings_revision_id = $1
ORDER BY id
`

func (q *Queries) ListRevisionRateLimitsByRevisionID(ctx context.Context, workerSettingsRevisionID int32) ([]RevisionRateLimit, error) {
	rows, err := q.db.Query(ctx, listRevisionRateLimitsByRevisionID, workerSettingsRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionRateLimit
	for rows.Next() {
		var i RevisionRateLimit
		if err := rows.Scan(
			&i.ID,
			&i.WorkerSettingsRevisionID,
			&i.Limit,
			&i.WindowSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRevisionRateLimit = `-- name: UpdateRevisionRateLimit :one
UPDATE "revision_rate_limit"
SET "limit" = $2, window_seconds = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, worker_settings_revision_id, "limit", window_seconds, created_at, updated_at
`

type UpdateRevisionRateLimitParams struct {
	ID            int32 `json:"id"`
	Limit         int32 `json:"limit"`
	WindowSeconds int32 `json:"window_seconds"`
}

func (q *Queries) UpdateRevisionRateLimit(ctx context.Context, arg UpdateRevisionRateLimitParams) (RevisionRateLimit, error) {
	row := q.db.QueryRow(ctx, updateRevisionRateLimit, arg.ID, arg.Limit, arg.WindowSeconds)
	var i RevisionRateLimit
	err := row.Scan(
		&i.ID,
		&i.WorkerSettingsRevisionID,
		&i.Limit,
		&i.WindowSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
