// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_run.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExperimentVariantRunsSince = `-- name: CountExperimentVariantRunsSince :many
SELECT
    wr.workflow_experiment_variant_id::int AS workflow_experiment_variant_id,
    COUNT(*)::int AS run_count
FROM "workflow_run" wr
JOIN "message" m ON m.id = wr.message_id
WHERE wr.workflow_experiment_scope_id = $1
  AND wr.workflow_experiment_variant_id IS NOT NULL
  AND m.created_at >= $2
GROUP BY wr.workflow_experiment_variant_id
ORDER BY wr.workflow_experiment_variant_id
`

type CountExperimentVariantRunsSinceParams struct {
	WorkflowExperimentScopeID pgtype.Int4      `json:"workflow_experiment_scope_id"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
}

type CountExperimentVariantRunsSinceRow struct {
	WorkflowExperimentVariantID int32 `json:"workflow_experiment_variant_id"`
	RunCount                    int32 `json:"run_count"`
}

func (q *Queries) CountExperimentVariantRunsSince(ctx context.Context, arg CountExperimentVariantRunsSinceParams) ([]CountExperimentVariantRunsSinceRow, error) {
	rows, err := q.db.Query(ctx, countExperimentVariantRunsSince, arg.WorkflowExperimentScopeID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountExperimentVariantRunsSinceRow
	for rows.Next() {
		var i CountExperimentVariantRunsSinceRow
		if err := rows.Scan(&i.WorkflowExperimentVariantID, &i.RunCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO "workflow_run" (
    workflow_version_id,
    message_id,
    temporal_workflow_id,
    status,
    workflow_experiment_id,
    workflow_experiment_scope_id,
    workflow_experiment_variant_id,
    input_schema_compatibility_id,
    selection_reason,
    version_input_data,
    routing_decision
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE(NULLIF($9, ''), 'standard'), COALESCE($10, '{}'::jsonb), $11)
RETURNING id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision
`

type CreateWorkflowRunParams struct {
	WorkflowVersionID           int32       `json:"workflow_version_id"`
	MessageID                   int32       `json:"message_id"`
	TemporalWorkflowID          pgtype.Text `json:"temporal_workflow_id"`
	Status                      string      `json:"status"`
	WorkflowExperimentID        pgtype.Int4 `json:"workflow_experiment_id"`
	WorkflowExperimentScopeID   pgtype.Int4 `json:"workflow_experiment_scope_id"`
	WorkflowExperimentVariantID pgtype.Int4 `json:"workflow_experiment_variant_id"`
	InputSchemaCompatibilityID  pgtype.Int4 `json:"input_schema_compatibility_id"`
	Column9                     interface{} `json:"column_9"`
	Column10                    interface{} `json:"column_10"`
	RoutingDecision             []byte      `json:"routing_decision"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.WorkflowVersionID,
		arg.MessageID,
		arg.TemporalWorkflowID,
		arg.Status,
		arg.WorkflowExperimentID,
		arg.WorkflowExperimentScopeID,
		arg.WorkflowExperimentVariantID,
		arg.InputSchemaCompatibilityID,
		arg.Column9,
		arg.Column10,
		arg.RoutingDecision,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.MessageID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowExperimentID,
		&i.WorkflowExperimentScopeID,
		&i.WorkflowExperimentVariantID,
		&i.InputSchemaCompatibilityID,
		&i.SelectionReason,
		&i.VersionInputData,
		&i.RoutingDecision,
	)
	return i, err
}

const getLatestWorkflowRunByMessageID = `-- name: GetLatestWorkflowRunByMessageID :one
SELECT id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision FROM "workflow_run"
WHERE message_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestWorkflowRunByMessageID(ctx context.Context, messageID int32) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowRunByMessageID, messageID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.MessageID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowExperimentID,
		&i.WorkflowExperimentScopeID,
		&i.WorkflowExperimentVariantID,
		&i.InputSchemaCompatibilityID,
		&i.SelectionReason,
		&i.VersionInputData,
		&i.RoutingDecision,
	)
	return i, err
}

const getWorkflowRunByID = `-- name: GetWorkflowRunByID :one
SELECT id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision FROM "workflow_run"
WHERE id = $1
`

func (q *Queries) GetWorkflowRunByID(ctx context.Context, id int32) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByID, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.MessageID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowExperimentID,
		&i.WorkflowExperimentScopeID,
		&i.WorkflowExperimentVariantID,
		&i.InputSchemaCompatibilityID,
		&i.SelectionReason,
		&i.VersionInputData,
		&i.RoutingDecision,
	)
	return i, err
}

const getWorkflowRunByTemporalID = `-- name: GetWorkflowRunByTemporalID :one
SELECT id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision FROM "workflow_run"
WHERE temporal_workflow_id = $1
LIMIT 1
`

func (q *Queries) GetWorkflowRunByTemporalID(ctx context.Context, temporalWorkflowID pgtype.Text) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByTemporalID, temporalWorkflowID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.MessageID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowExperimentID,
		&i.WorkflowExperimentScopeID,
		&i.WorkflowExperimentVariantID,
		&i.InputSchemaCompatibilityID,
		&i.SelectionReason,
		&i.VersionInputData,
		&i.RoutingDecision,
	)
	return i, err
}

const listWorkflowRunsByMessageID = `-- name: ListWorkflowRunsByMessageID :many
SELECT id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision FROM "workflow_run"
WHERE message_id = $1
ORDER BY id
`

func (q *Queries) ListWorkflowRunsByMessageID(ctx context.Context, messageID int32) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowVersionID,
			&i.MessageID,
			&i.TemporalWorkflowID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.WorkflowExperimentID,
			&i.WorkflowExperimentScopeID,
			&i.WorkflowExperimentVariantID,
			&i.InputSchemaCompatibilityID,
			&i.SelectionReason,
			&i.VersionInputData,
			&i.RoutingDecision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStarted = `-- name: UpdateWorkflowRunStarted :one
UPDATE "workflow_run"
SET status = 'running', started_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision
`

func (q *Queries) UpdateWorkflowRunStarted(ctx context.Context, id int32) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunStarted, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.MessageID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowExperimentID,
		&i.WorkflowExperimentScopeID,
		&i.WorkflowExperimentVariantID,
		&i.InputSchemaCompatibilityID,
		&i.SelectionReason,
		&i.VersionInputData,
		&i.RoutingDecision,
	)
	return i, err
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :one
UPDATE "workflow_run"
SET status = $2, completed_at = $3, error_message = $4
WHERE id = $1
RETURNING id, workflow_version_id, message_id, temporal_workflow_id, status, started_at, completed_at, error_message, workflow_experiment_id, workflow_experiment_scope_id, workflow_experiment_variant_id, input_schema_compatibility_id, selection_reason, version_input_data, routing_decision
`

type UpdateWorkflowRunStatusParams struct {
	ID           int32            `json:"id"`
	Status       string           `json:"status"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
	ErrorMessage pgtype.Text      `json:"error_message"`
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowVersionID,
		&i.MessageID,
		&i.TemporalWorkflowID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.WorkflowExperimentID,
		&i.WorkflowExperimentScopeID,
		&i.WorkflowExperimentVariantID,
		&i.InputSchemaCompatibilityID,
		&i.SelectionReason,
		&i.VersionInputData,
		&i.RoutingDecision,
	)
	return i, err
}
