// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow_token.sql

package db

import (
	"context"
)

const checkWorkflowAccess = `-- name: CheckWorkflowAccess :one
SELECT COUNT(*) > 0 AS has_access
FROM "workflow_token" wt
JOIN "system_token" st ON st.id = wt.system_token_id
WHERE wt.workflow_id = $1
  AND st.public_token = $2
  AND st.is_active = TRUE
  AND st.deleted_at IS NULL
`

type CheckWorkflowAccessParams struct {
	WorkflowID  int32  `json:"workflow_id"`
	PublicToken string `json:"public_token"`
}

func (q *Queries) CheckWorkflowAccess(ctx context.Context, arg CheckWorkflowAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkflowAccess, arg.WorkflowID, arg.PublicToken)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const grantWorkflowToken = `-- name: GrantWorkflowToken :exec
INSERT INTO "workflow_token" (system_token_id, workflow_id)
VALUES ($1, $2)
ON CONFLICT (system_token_id, workflow_id) DO NOTHING
`

type GrantWorkflowTokenParams struct {
	SystemTokenID int32 `json:"system_token_id"`
	WorkflowID    int32 `json:"workflow_id"`
}

func (q *Queries) GrantWorkflowToken(ctx context.Context, arg GrantWorkflowTokenParams) error {
	_, err := q.db.Exec(ctx, grantWorkflowToken, arg.SystemTokenID, arg.WorkflowID)
	return err
}

const listWorkflowTokensBySystemTokenID = `-- name: ListWorkflowTokensBySystemTokenID :many
SELECT system_token_id, workflow_id, granted_at FROM "workflow_token"
WHERE system_token_id = $1
ORDER BY workflow_id
`

func (q *Queries) ListWorkflowTokensBySystemTokenID(ctx context.Context, systemTokenID int32) ([]WorkflowToken, error) {
	rows, err := q.db.Query(ctx, listWorkflowTokensBySystemTokenID, systemTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowToken
	for rows.Next() {
		var i WorkflowToken
		if err := rows.Scan(&i.SystemTokenID, &i.WorkflowID, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTokensByWorkflowID = `-- name: ListWorkflowTokensByWorkflowID :many
SELECT system_token_id, workflow_id, granted_at FROM "workflow_token"
WHERE workflow_id = $1
ORDER BY system_token_id
`

func (q *Queries) ListWorkflowTokensByWorkflowID(ctx context.Context, workflowID int32) ([]WorkflowToken, error) {
	rows, err := q.db.Query(ctx, listWorkflowTokensByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowToken
	for rows.Next() {
		var i WorkflowToken
		if err := rows.Scan(&i.SystemTokenID, &i.WorkflowID, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkflowToken = `-- name: RevokeWorkflowToken :exec
DELETE FROM "workflow_token"
WHERE system_token_id = $1 AND workflow_id = $2
`

type RevokeWorkflowTokenParams struct {
	SystemTokenID int32 `json:"system_token_id"`
	WorkflowID    int32 `json:"workflow_id"`
}

func (q *Queries) RevokeWorkflowToken(ctx context.Context, arg RevokeWorkflowTokenParams) error {
	_, err := q.db.Exec(ctx, revokeWorkflowToken, arg.SystemTokenID, arg.WorkflowID)
	return err
}
