# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Cactus check lint and test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: &go-modules
          - apps/core
          - apps/workers/smtp
          - apps/workers/telegram
          - apps/workers/template
          - cli
          - libs/bus
          - libs/config
          - libs/logger
          - libs/migrations
          - libs/permissions
          - libs/pipeline
          - libs/worker
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          working-directory: ${{ matrix.module }}
          args: '--timeout=3m ./...'
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: *go-modules
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Unit tests
        working-directory: ${{ matrix.module }}
        run: go test -v -race -count=100 -timeout=1m ./...
